// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// ACLRuleApplyConfiguration represents a declarative configuration of the ACLRule type for use
// with apply.
//
// ACLRule matches one IP family. Ports require an explicit TCP or UDP protocol.
type ACLRuleApplyConfiguration struct {
	Name            *apiv1alpha1.TrafficPolicyName `json:"name,omitempty"`
	Priority        *uint32                        `json:"priority,omitempty"`
	Action          *apiv1alpha1.ACLAction         `json:"action,omitempty"`
	Source          *apiv1alpha1.NetworkPrefix     `json:"source,omitempty"`
	Destination     *apiv1alpha1.NetworkPrefix     `json:"destination,omitempty"`
	Protocol        *uint32                        `json:"protocol,omitempty"`
	SourcePort      *uint32                        `json:"sourcePort,omitempty"`
	DestinationPort *uint32                        `json:"destinationPort,omitempty"`
}

// ACLRuleApplyConfiguration constructs a declarative configuration of the ACLRule type for use with
// apply.
func ACLRule() *ACLRuleApplyConfiguration {
	return &ACLRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithName(value apiv1alpha1.TrafficPolicyName) *ACLRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithPriority(value uint32) *ACLRuleApplyConfiguration {
	b.Priority = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithAction(value apiv1alpha1.ACLAction) *ACLRuleApplyConfiguration {
	b.Action = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithSource(value apiv1alpha1.NetworkPrefix) *ACLRuleApplyConfiguration {
	b.Source = &value
	return b
}

// WithDestination sets the Destination field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Destination field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithDestination(value apiv1alpha1.NetworkPrefix) *ACLRuleApplyConfiguration {
	b.Destination = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithProtocol(value uint32) *ACLRuleApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithSourcePort sets the SourcePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourcePort field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithSourcePort(value uint32) *ACLRuleApplyConfiguration {
	b.SourcePort = &value
	return b
}

// WithDestinationPort sets the DestinationPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DestinationPort field is set to the value of the last call.
func (b *ACLRuleApplyConfiguration) WithDestinationPort(value uint32) *ACLRuleApplyConfiguration {
	b.DestinationPort = &value
	return b
}
