// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactContentRefApplyConfiguration represents a declarative configuration of the ArtifactContentRef type for use
// with apply.
//
// ArtifactContentRef pins an immutable object, including its UID, so deleting
// and recreating an identically named source cannot replace approved bytes.
type ArtifactContentRefApplyConfiguration struct {
	Kind *string `json:"kind,omitempty"`
	Name *string `json:"name,omitempty"`
	UID  *string `json:"uid,omitempty"`
	Key  *string `json:"key,omitempty"`
}

// ArtifactContentRefApplyConfiguration constructs a declarative configuration of the ArtifactContentRef type for use with
// apply.
func ArtifactContentRef() *ArtifactContentRefApplyConfiguration {
	return &ArtifactContentRefApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ArtifactContentRefApplyConfiguration) WithKind(value string) *ArtifactContentRefApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ArtifactContentRefApplyConfiguration) WithName(value string) *ArtifactContentRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ArtifactContentRefApplyConfiguration) WithUID(value string) *ArtifactContentRefApplyConfiguration {
	b.UID = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ArtifactContentRefApplyConfiguration) WithKey(value string) *ArtifactContentRefApplyConfiguration {
	b.Key = &value
	return b
}
