// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactAgentOptionsApplyConfiguration represents a declarative configuration of the ArtifactAgentOptions type for use
// with apply.
//
// ArtifactAgentOptions is rendered into a fixed unit; unit text and arbitrary
// flags cannot be supplied as artifact content.
type ArtifactAgentOptionsApplyConfiguration struct {
	HostConfig    *bool   `json:"hostConfig,omitempty"`
	HostGuard     *bool   `json:"hostGuard,omitempty"`
	BindAddress   *string `json:"bindAddress,omitempty"`
	Port          *int    `json:"port,omitempty"`
	ReadOnly      *bool   `json:"readOnly,omitempty"`
	VLANAuthority *bool   `json:"vlanAuthority,omitempty"`
	Breakout      *bool   `json:"breakout,omitempty"`
	Network       *bool   `json:"network,omitempty"`
	FRRMigration  *bool   `json:"frrMigration,omitempty"`
	TrafficPolicy *bool   `json:"trafficPolicy,omitempty"`
	Redundancy    *bool   `json:"redundancy,omitempty"`
	Artifacts     *bool   `json:"artifacts,omitempty"`
}

// ArtifactAgentOptionsApplyConfiguration constructs a declarative configuration of the ArtifactAgentOptions type for use with
// apply.
func ArtifactAgentOptions() *ArtifactAgentOptionsApplyConfiguration {
	return &ArtifactAgentOptionsApplyConfiguration{}
}

// WithHostConfig sets the HostConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostConfig field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithHostConfig(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.HostConfig = &value
	return b
}

// WithHostGuard sets the HostGuard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostGuard field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithHostGuard(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.HostGuard = &value
	return b
}

// WithBindAddress sets the BindAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindAddress field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithBindAddress(value string) *ArtifactAgentOptionsApplyConfiguration {
	b.BindAddress = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithPort(value int) *ArtifactAgentOptionsApplyConfiguration {
	b.Port = &value
	return b
}

// WithReadOnly sets the ReadOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadOnly field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithReadOnly(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.ReadOnly = &value
	return b
}

// WithVLANAuthority sets the VLANAuthority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANAuthority field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithVLANAuthority(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.VLANAuthority = &value
	return b
}

// WithBreakout sets the Breakout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Breakout field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithBreakout(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.Breakout = &value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithNetwork(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.Network = &value
	return b
}

// WithFRRMigration sets the FRRMigration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FRRMigration field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithFRRMigration(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.FRRMigration = &value
	return b
}

// WithTrafficPolicy sets the TrafficPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrafficPolicy field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithTrafficPolicy(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.TrafficPolicy = &value
	return b
}

// WithRedundancy sets the Redundancy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redundancy field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithRedundancy(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.Redundancy = &value
	return b
}

// WithArtifacts sets the Artifacts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Artifacts field is set to the value of the last call.
func (b *ArtifactAgentOptionsApplyConfiguration) WithArtifacts(value bool) *ArtifactAgentOptionsApplyConfiguration {
	b.Artifacts = &value
	return b
}
