// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactMACHookSpecApplyConfiguration represents a declarative configuration of the ArtifactMACHookSpec type for use
// with apply.
type ArtifactMACHookSpecApplyConfiguration struct {
	Kind             *string                               `json:"kind,omitempty"`
	SourceHookSHA256 *string                               `json:"sourceHookSHA256,omitempty"`
	SourceHookRef    *ArtifactContentRefApplyConfiguration `json:"sourceHookRef,omitempty"`
	HelperSHA256     *string                               `json:"helperSHA256,omitempty"`
	HelperRef        *ArtifactContentRefApplyConfiguration `json:"helperRef,omitempty"`
}

// ArtifactMACHookSpecApplyConfiguration constructs a declarative configuration of the ArtifactMACHookSpec type for use with
// apply.
func ArtifactMACHookSpec() *ArtifactMACHookSpecApplyConfiguration {
	return &ArtifactMACHookSpecApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ArtifactMACHookSpecApplyConfiguration) WithKind(value string) *ArtifactMACHookSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithSourceHookSHA256 sets the SourceHookSHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceHookSHA256 field is set to the value of the last call.
func (b *ArtifactMACHookSpecApplyConfiguration) WithSourceHookSHA256(value string) *ArtifactMACHookSpecApplyConfiguration {
	b.SourceHookSHA256 = &value
	return b
}

// WithSourceHookRef sets the SourceHookRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceHookRef field is set to the value of the last call.
func (b *ArtifactMACHookSpecApplyConfiguration) WithSourceHookRef(value *ArtifactContentRefApplyConfiguration) *ArtifactMACHookSpecApplyConfiguration {
	b.SourceHookRef = value
	return b
}

// WithHelperSHA256 sets the HelperSHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelperSHA256 field is set to the value of the last call.
func (b *ArtifactMACHookSpecApplyConfiguration) WithHelperSHA256(value string) *ArtifactMACHookSpecApplyConfiguration {
	b.HelperSHA256 = &value
	return b
}

// WithHelperRef sets the HelperRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelperRef field is set to the value of the last call.
func (b *ArtifactMACHookSpecApplyConfiguration) WithHelperRef(value *ArtifactContentRefApplyConfiguration) *ArtifactMACHookSpecApplyConfiguration {
	b.HelperRef = value
	return b
}
