// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactFileApplyConfiguration represents a declarative configuration of the ArtifactFile type for use
// with apply.
type ArtifactFileApplyConfiguration struct {
	Slot *string `json:"slot,omitempty"`
	// SHA256 is over the concatenation of the referenced chunks in order.
	SHA256 *string `json:"sha256,omitempty"`
	// Chunks permit binaries larger than the Kubernetes single-object limit.
	Chunks []ArtifactContentRefApplyConfiguration `json:"chunks,omitempty"`
}

// ArtifactFileApplyConfiguration constructs a declarative configuration of the ArtifactFile type for use with
// apply.
func ArtifactFile() *ArtifactFileApplyConfiguration {
	return &ArtifactFileApplyConfiguration{}
}

// WithSlot sets the Slot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slot field is set to the value of the last call.
func (b *ArtifactFileApplyConfiguration) WithSlot(value string) *ArtifactFileApplyConfiguration {
	b.Slot = &value
	return b
}

// WithSHA256 sets the SHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SHA256 field is set to the value of the last call.
func (b *ArtifactFileApplyConfiguration) WithSHA256(value string) *ArtifactFileApplyConfiguration {
	b.SHA256 = &value
	return b
}

// WithChunks adds the given value to the Chunks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Chunks field.
func (b *ArtifactFileApplyConfiguration) WithChunks(values ...*ArtifactContentRefApplyConfiguration) *ArtifactFileApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChunks")
		}
		b.Chunks = append(b.Chunks, *values[i])
	}
	return b
}
