// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactBootstrapSpecApplyConfiguration represents a declarative configuration of the ArtifactBootstrapSpec type for use
// with apply.
//
// ArtifactBootstrapSpec declares the immutable recovery baseline. The main
// agent independently enforces it so recovery never depends on replacing itself.
type ArtifactBootstrapSpecApplyConfiguration struct {
	HostRecovery     *ArtifactHostRecoverySpecApplyConfiguration `json:"hostRecovery,omitempty"`
	SupervisorSHA256 *string                                     `json:"supervisorSHA256,omitempty"`
	SupervisorChunks []ArtifactContentRefApplyConfiguration      `json:"supervisorChunks,omitempty"`
	PolicySHA256     *string                                     `json:"policySHA256,omitempty"`
	PolicyRef        *ArtifactContentRefApplyConfiguration       `json:"policyRef,omitempty"`
	// SHA of the fixed unit generated by the agent protocol version.
	UnitSHA256 *string `json:"unitSHA256,omitempty"`
}

// ArtifactBootstrapSpecApplyConfiguration constructs a declarative configuration of the ArtifactBootstrapSpec type for use with
// apply.
func ArtifactBootstrapSpec() *ArtifactBootstrapSpecApplyConfiguration {
	return &ArtifactBootstrapSpecApplyConfiguration{}
}

// WithHostRecovery sets the HostRecovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostRecovery field is set to the value of the last call.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithHostRecovery(value *ArtifactHostRecoverySpecApplyConfiguration) *ArtifactBootstrapSpecApplyConfiguration {
	b.HostRecovery = value
	return b
}

// WithSupervisorSHA256 sets the SupervisorSHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SupervisorSHA256 field is set to the value of the last call.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithSupervisorSHA256(value string) *ArtifactBootstrapSpecApplyConfiguration {
	b.SupervisorSHA256 = &value
	return b
}

// WithSupervisorChunks adds the given value to the SupervisorChunks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupervisorChunks field.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithSupervisorChunks(values ...*ArtifactContentRefApplyConfiguration) *ArtifactBootstrapSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSupervisorChunks")
		}
		b.SupervisorChunks = append(b.SupervisorChunks, *values[i])
	}
	return b
}

// WithPolicySHA256 sets the PolicySHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicySHA256 field is set to the value of the last call.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithPolicySHA256(value string) *ArtifactBootstrapSpecApplyConfiguration {
	b.PolicySHA256 = &value
	return b
}

// WithPolicyRef sets the PolicyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyRef field is set to the value of the last call.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithPolicyRef(value *ArtifactContentRefApplyConfiguration) *ArtifactBootstrapSpecApplyConfiguration {
	b.PolicyRef = value
	return b
}

// WithUnitSHA256 sets the UnitSHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnitSHA256 field is set to the value of the last call.
func (b *ArtifactBootstrapSpecApplyConfiguration) WithUnitSHA256(value string) *ArtifactBootstrapSpecApplyConfiguration {
	b.UnitSHA256 = &value
	return b
}
