// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostSecretKeyReferenceApplyConfiguration represents a declarative configuration of the HostSecretKeyReference type for use
// with apply.
type HostSecretKeyReferenceApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
	Key       *string `json:"key,omitempty"`
}

// HostSecretKeyReferenceApplyConfiguration constructs a declarative configuration of the HostSecretKeyReference type for use with
// apply.
func HostSecretKeyReference() *HostSecretKeyReferenceApplyConfiguration {
	return &HostSecretKeyReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *HostSecretKeyReferenceApplyConfiguration) WithNamespace(value string) *HostSecretKeyReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HostSecretKeyReferenceApplyConfiguration) WithName(value string) *HostSecretKeyReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *HostSecretKeyReferenceApplyConfiguration) WithKey(value string) *HostSecretKeyReferenceApplyConfiguration {
	b.Key = &value
	return b
}
