// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// NetworkResourceStatusApplyConfiguration represents a declarative configuration of the NetworkResourceStatus type for use
// with apply.
//
// NetworkResourceStatus reports independent proof, not inferred forwarding health.
type NetworkResourceStatusApplyConfiguration struct {
	ObservedGeneration    *int64 `json:"observedGeneration,omitempty"`
	Exists                *bool  `json:"exists,omitempty"`
	ConfigurationVerified *bool  `json:"configurationVerified,omitempty"`
	RuntimeVerified       *bool  `json:"runtimeVerified,omitempty"`
	PersistenceVerified   *bool  `json:"persistenceVerified,omitempty"`
	// Observed preserves the agent's structured observation without interpreting it.
	Observed *runtime.RawExtension `json:"observed,omitempty"`
	// Ready, Synced, ConfigurationReady, RuntimeReady and PersistenceReady are independent.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// NetworkResourceStatusApplyConfiguration constructs a declarative configuration of the NetworkResourceStatus type for use with
// apply.
func NetworkResourceStatus() *NetworkResourceStatusApplyConfiguration {
	return &NetworkResourceStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithObservedGeneration(value int64) *NetworkResourceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithExists sets the Exists field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exists field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithExists(value bool) *NetworkResourceStatusApplyConfiguration {
	b.Exists = &value
	return b
}

// WithConfigurationVerified sets the ConfigurationVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigurationVerified field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithConfigurationVerified(value bool) *NetworkResourceStatusApplyConfiguration {
	b.ConfigurationVerified = &value
	return b
}

// WithRuntimeVerified sets the RuntimeVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeVerified field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithRuntimeVerified(value bool) *NetworkResourceStatusApplyConfiguration {
	b.RuntimeVerified = &value
	return b
}

// WithPersistenceVerified sets the PersistenceVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistenceVerified field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithPersistenceVerified(value bool) *NetworkResourceStatusApplyConfiguration {
	b.PersistenceVerified = &value
	return b
}

// WithObserved sets the Observed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Observed field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithObserved(value runtime.RawExtension) *NetworkResourceStatusApplyConfiguration {
	b.Observed = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *NetworkResourceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
