// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// QoSMapEntryApplyConfiguration represents a declarative configuration of the QoSMapEntry type for use
// with apply.
type QoSMapEntryApplyConfiguration struct {
	From *uint32 `json:"from,omitempty"`
	To   *uint32 `json:"to,omitempty"`
}

// QoSMapEntryApplyConfiguration constructs a declarative configuration of the QoSMapEntry type for use with
// apply.
func QoSMapEntry() *QoSMapEntryApplyConfiguration {
	return &QoSMapEntryApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *QoSMapEntryApplyConfiguration) WithFrom(value uint32) *QoSMapEntryApplyConfiguration {
	b.From = &value
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *QoSMapEntryApplyConfiguration) WithTo(value uint32) *QoSMapEntryApplyConfiguration {
	b.To = &value
	return b
}
