// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// QoSQueueBindingApplyConfiguration represents a declarative configuration of the QoSQueueBinding type for use
// with apply.
type QoSQueueBindingApplyConfiguration struct {
	Index     *uint32                    `json:"index,omitempty"`
	Scheduler *apiv1alpha1.QoSPolicyName `json:"scheduler,omitempty"`
}

// QoSQueueBindingApplyConfiguration constructs a declarative configuration of the QoSQueueBinding type for use with
// apply.
func QoSQueueBinding() *QoSQueueBindingApplyConfiguration {
	return &QoSQueueBindingApplyConfiguration{}
}

// WithIndex sets the Index field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Index field is set to the value of the last call.
func (b *QoSQueueBindingApplyConfiguration) WithIndex(value uint32) *QoSQueueBindingApplyConfiguration {
	b.Index = &value
	return b
}

// WithScheduler sets the Scheduler field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheduler field is set to the value of the last call.
func (b *QoSQueueBindingApplyConfiguration) WithScheduler(value apiv1alpha1.QoSPolicyName) *QoSQueueBindingApplyConfiguration {
	b.Scheduler = &value
	return b
}
