// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// StaticRouteNextHopApplyConfiguration represents a declarative configuration of the StaticRouteNextHop type for use
// with apply.
type StaticRouteNextHopApplyConfiguration struct {
	Address       *apiv1alpha1.NetworkIP `json:"address,omitempty"`
	InterfaceName *string                `json:"interfaceName,omitempty"`
	Distance      *uint32                `json:"distance,omitempty"`
}

// StaticRouteNextHopApplyConfiguration constructs a declarative configuration of the StaticRouteNextHop type for use with
// apply.
func StaticRouteNextHop() *StaticRouteNextHopApplyConfiguration {
	return &StaticRouteNextHopApplyConfiguration{}
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *StaticRouteNextHopApplyConfiguration) WithAddress(value apiv1alpha1.NetworkIP) *StaticRouteNextHopApplyConfiguration {
	b.Address = &value
	return b
}

// WithInterfaceName sets the InterfaceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterfaceName field is set to the value of the last call.
func (b *StaticRouteNextHopApplyConfiguration) WithInterfaceName(value string) *StaticRouteNextHopApplyConfiguration {
	b.InterfaceName = &value
	return b
}

// WithDistance sets the Distance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Distance field is set to the value of the last call.
func (b *StaticRouteNextHopApplyConfiguration) WithDistance(value uint32) *StaticRouteNextHopApplyConfiguration {
	b.Distance = &value
	return b
}
