// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchBufferProfileSpecApplyConfiguration represents a declarative configuration of the SwitchBufferProfileSpec type for use
// with apply.
//
// SwitchBufferProfileSpec owns BUFFER_PROFILE fields. Threshold mode must match the pool.
type SwitchBufferProfileSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.BufferName `json:"name,omitempty"`
	Pool                                  *apiv1alpha1.BufferName `json:"pool,omitempty"`
	// Size is reserved buffer bytes, including an explicit zero.
	Size             *uint64 `json:"size,omitempty"`
	DynamicThreshold *int32  `json:"dynamicThreshold,omitempty"`
	StaticThreshold  *uint64 `json:"staticThreshold,omitempty"`
	Xon              *uint64 `json:"xon,omitempty"`
	Xoff             *uint64 `json:"xoff,omitempty"`
	XonOffset        *uint64 `json:"xonOffset,omitempty"`
}

// SwitchBufferProfileSpecApplyConfiguration constructs a declarative configuration of the SwitchBufferProfileSpec type for use with
// apply.
func SwitchBufferProfileSpec() *SwitchBufferProfileSpecApplyConfiguration {
	return &SwitchBufferProfileSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchBufferProfileSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchBufferProfileSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithName(value apiv1alpha1.BufferName) *SwitchBufferProfileSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithPool sets the Pool field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pool field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithPool(value apiv1alpha1.BufferName) *SwitchBufferProfileSpecApplyConfiguration {
	b.Pool = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithSize(value uint64) *SwitchBufferProfileSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithDynamicThreshold sets the DynamicThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicThreshold field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithDynamicThreshold(value int32) *SwitchBufferProfileSpecApplyConfiguration {
	b.DynamicThreshold = &value
	return b
}

// WithStaticThreshold sets the StaticThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StaticThreshold field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithStaticThreshold(value uint64) *SwitchBufferProfileSpecApplyConfiguration {
	b.StaticThreshold = &value
	return b
}

// WithXon sets the Xon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Xon field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithXon(value uint64) *SwitchBufferProfileSpecApplyConfiguration {
	b.Xon = &value
	return b
}

// WithXoff sets the Xoff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Xoff field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithXoff(value uint64) *SwitchBufferProfileSpecApplyConfiguration {
	b.Xoff = &value
	return b
}

// WithXonOffset sets the XonOffset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the XonOffset field is set to the value of the last call.
func (b *SwitchBufferProfileSpecApplyConfiguration) WithXonOffset(value uint64) *SwitchBufferProfileSpecApplyConfiguration {
	b.XonOffset = &value
	return b
}
