// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SwitchPortBreakoutStatusApplyConfiguration represents a declarative configuration of the SwitchPortBreakoutStatus type for use
// with apply.
//
// SwitchPortBreakoutStatus reports configuration, runtime and save proof, not
// carrier or forwarding health. Failed mutations never authorize inventory pruning.
type SwitchPortBreakoutStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// TargetIdentity mirrors the durable metadata binding; it is not authority.
	TargetIdentity *string `json:"targetIdentity,omitempty"`
	// Mode is the latest observed CONFIG_DB mode, not necessarily the desired mode.
	Mode           *string                                     `json:"mode,omitempty"`
	SupportedModes []string                                    `json:"supportedModes,omitempty"`
	Children       []SwitchPortBreakoutChildApplyConfiguration `json:"children,omitempty"`
	// PreviousChildren retains the pre-operation inventory across interrupted
	// attempts. Only a subsequent confirmed operation can authorize its cleanup.
	PreviousChildren      []SwitchPortBreakoutChildApplyConfiguration `json:"previousChildren,omitempty"`
	ConfigurationVerified *bool                                       `json:"configurationVerified,omitempty"`
	// RuntimeVerified confirms APPL_DB and kernel layout, not cable/link health.
	RuntimeVerified     *bool `json:"runtimeVerified,omitempty"`
	PersistenceVerified *bool `json:"persistenceVerified,omitempty"`
	// Pending indicates an unresolved operation; recovery must not blindly rerun CLI.
	Pending *bool   `json:"pending,omitempty"`
	Message *string `json:"message,omitempty"`
	// Ready, ConfigurationReady, RuntimeReady, PersistenceReady and Progressing
	// describe this generation independently.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SwitchPortBreakoutStatusApplyConfiguration constructs a declarative configuration of the SwitchPortBreakoutStatus type for use with
// apply.
func SwitchPortBreakoutStatus() *SwitchPortBreakoutStatusApplyConfiguration {
	return &SwitchPortBreakoutStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithObservedGeneration(value int64) *SwitchPortBreakoutStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithTargetIdentity sets the TargetIdentity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIdentity field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithTargetIdentity(value string) *SwitchPortBreakoutStatusApplyConfiguration {
	b.TargetIdentity = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithMode(value string) *SwitchPortBreakoutStatusApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSupportedModes adds the given value to the SupportedModes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SupportedModes field.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithSupportedModes(values ...string) *SwitchPortBreakoutStatusApplyConfiguration {
	for i := range values {
		b.SupportedModes = append(b.SupportedModes, values[i])
	}
	return b
}

// WithChildren adds the given value to the Children field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Children field.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithChildren(values ...*SwitchPortBreakoutChildApplyConfiguration) *SwitchPortBreakoutStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChildren")
		}
		b.Children = append(b.Children, *values[i])
	}
	return b
}

// WithPreviousChildren adds the given value to the PreviousChildren field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PreviousChildren field.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithPreviousChildren(values ...*SwitchPortBreakoutChildApplyConfiguration) *SwitchPortBreakoutStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPreviousChildren")
		}
		b.PreviousChildren = append(b.PreviousChildren, *values[i])
	}
	return b
}

// WithConfigurationVerified sets the ConfigurationVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigurationVerified field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithConfigurationVerified(value bool) *SwitchPortBreakoutStatusApplyConfiguration {
	b.ConfigurationVerified = &value
	return b
}

// WithRuntimeVerified sets the RuntimeVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeVerified field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithRuntimeVerified(value bool) *SwitchPortBreakoutStatusApplyConfiguration {
	b.RuntimeVerified = &value
	return b
}

// WithPersistenceVerified sets the PersistenceVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistenceVerified field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithPersistenceVerified(value bool) *SwitchPortBreakoutStatusApplyConfiguration {
	b.PersistenceVerified = &value
	return b
}

// WithPending sets the Pending field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pending field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithPending(value bool) *SwitchPortBreakoutStatusApplyConfiguration {
	b.Pending = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithMessage(value string) *SwitchPortBreakoutStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SwitchPortBreakoutStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SwitchPortBreakoutStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
