// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchPortBreakoutChildApplyConfiguration represents a declarative configuration of the SwitchPortBreakoutChild type for use
// with apply.
//
// SwitchPortBreakoutChild is an observed native child, independent of agent types.
type SwitchPortBreakoutChildApplyConfiguration struct {
	Name       *string                 `json:"name,omitempty"`
	Lanes      *string                 `json:"lanes,omitempty"`
	Speed      *string                 `json:"speed,omitempty"`
	AdminState *apiv1alpha1.AdminState `json:"adminState,omitempty"`
	MTU        *string                 `json:"mtu,omitempty"`
}

// SwitchPortBreakoutChildApplyConfiguration constructs a declarative configuration of the SwitchPortBreakoutChild type for use with
// apply.
func SwitchPortBreakoutChild() *SwitchPortBreakoutChildApplyConfiguration {
	return &SwitchPortBreakoutChildApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchPortBreakoutChildApplyConfiguration) WithName(value string) *SwitchPortBreakoutChildApplyConfiguration {
	b.Name = &value
	return b
}

// WithLanes sets the Lanes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lanes field is set to the value of the last call.
func (b *SwitchPortBreakoutChildApplyConfiguration) WithLanes(value string) *SwitchPortBreakoutChildApplyConfiguration {
	b.Lanes = &value
	return b
}

// WithSpeed sets the Speed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Speed field is set to the value of the last call.
func (b *SwitchPortBreakoutChildApplyConfiguration) WithSpeed(value string) *SwitchPortBreakoutChildApplyConfiguration {
	b.Speed = &value
	return b
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *SwitchPortBreakoutChildApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *SwitchPortBreakoutChildApplyConfiguration {
	b.AdminState = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *SwitchPortBreakoutChildApplyConfiguration) WithMTU(value string) *SwitchPortBreakoutChildApplyConfiguration {
	b.MTU = &value
	return b
}
