// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchQoSBindingSpecApplyConfiguration represents a declarative configuration of the SwitchQoSBindingSpec type for use
// with apply.
//
// SwitchQoSBindingSpec references existing, applied maps and schedulers on one data port.
type SwitchQoSBindingSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	InterfaceName                         *string                             `json:"interfaceName,omitempty"`
	DSCPToTC                              *apiv1alpha1.QoSPolicyName          `json:"dscpToTC,omitempty"`
	Dot1pToTC                             *apiv1alpha1.QoSPolicyName          `json:"dot1pToTC,omitempty"`
	TCToQueue                             *apiv1alpha1.QoSPolicyName          `json:"tcToQueue,omitempty"`
	Queues                                []QoSQueueBindingApplyConfiguration `json:"queues,omitempty"`
}

// SwitchQoSBindingSpecApplyConfiguration constructs a declarative configuration of the SwitchQoSBindingSpec type for use with
// apply.
func SwitchQoSBindingSpec() *SwitchQoSBindingSpecApplyConfiguration {
	return &SwitchQoSBindingSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchQoSBindingSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchQoSBindingSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithInterfaceName sets the InterfaceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterfaceName field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithInterfaceName(value string) *SwitchQoSBindingSpecApplyConfiguration {
	b.InterfaceName = &value
	return b
}

// WithDSCPToTC sets the DSCPToTC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DSCPToTC field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithDSCPToTC(value apiv1alpha1.QoSPolicyName) *SwitchQoSBindingSpecApplyConfiguration {
	b.DSCPToTC = &value
	return b
}

// WithDot1pToTC sets the Dot1pToTC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dot1pToTC field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithDot1pToTC(value apiv1alpha1.QoSPolicyName) *SwitchQoSBindingSpecApplyConfiguration {
	b.Dot1pToTC = &value
	return b
}

// WithTCToQueue sets the TCToQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCToQueue field is set to the value of the last call.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithTCToQueue(value apiv1alpha1.QoSPolicyName) *SwitchQoSBindingSpecApplyConfiguration {
	b.TCToQueue = &value
	return b
}

// WithQueues adds the given value to the Queues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Queues field.
func (b *SwitchQoSBindingSpecApplyConfiguration) WithQueues(values ...*QoSQueueBindingApplyConfiguration) *SwitchQoSBindingSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithQueues")
		}
		b.Queues = append(b.Queues, *values[i])
	}
	return b
}
