// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchQoSMapSpecApplyConfiguration represents a declarative configuration of the SwitchQoSMapSpec type for use
// with apply.
//
// SwitchQoSMapSpec defines a map; actual TC and queue bounds require device capabilities.
type SwitchQoSMapSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.QoSPolicyName      `json:"name,omitempty"`
	Type                                  *string                         `json:"type,omitempty"`
	Entries                               []QoSMapEntryApplyConfiguration `json:"entries,omitempty"`
}

// SwitchQoSMapSpecApplyConfiguration constructs a declarative configuration of the SwitchQoSMapSpec type for use with
// apply.
func SwitchQoSMapSpec() *SwitchQoSMapSpecApplyConfiguration {
	return &SwitchQoSMapSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchQoSMapSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchQoSMapSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchQoSMapSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchQoSMapSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchQoSMapSpecApplyConfiguration) WithName(value apiv1alpha1.QoSPolicyName) *SwitchQoSMapSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SwitchQoSMapSpecApplyConfiguration) WithType(value string) *SwitchQoSMapSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithEntries adds the given value to the Entries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Entries field.
func (b *SwitchQoSMapSpecApplyConfiguration) WithEntries(values ...*QoSMapEntryApplyConfiguration) *SwitchQoSMapSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEntries")
		}
		b.Entries = append(b.Entries, *values[i])
	}
	return b
}
