// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchACLPolicySpecApplyConfiguration represents a declarative configuration of the SwitchACLPolicySpec type for use
// with apply.
//
// SwitchACLPolicySpec stages an unbound ingress table with an explicit priority-1 catchall.
type SwitchACLPolicySpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.TrafficPolicyName `json:"name,omitempty"`
	Family                                *string                        `json:"family,omitempty"`
	DefaultAction                         *apiv1alpha1.ACLAction         `json:"defaultAction,omitempty"`
	Rules                                 []ACLRuleApplyConfiguration    `json:"rules,omitempty"`
}

// SwitchACLPolicySpecApplyConfiguration constructs a declarative configuration of the SwitchACLPolicySpec type for use with
// apply.
func SwitchACLPolicySpec() *SwitchACLPolicySpecApplyConfiguration {
	return &SwitchACLPolicySpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchACLPolicySpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchACLPolicySpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchACLPolicySpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchACLPolicySpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchACLPolicySpecApplyConfiguration) WithName(value apiv1alpha1.TrafficPolicyName) *SwitchACLPolicySpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithFamily sets the Family field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Family field is set to the value of the last call.
func (b *SwitchACLPolicySpecApplyConfiguration) WithFamily(value string) *SwitchACLPolicySpecApplyConfiguration {
	b.Family = &value
	return b
}

// WithDefaultAction sets the DefaultAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultAction field is set to the value of the last call.
func (b *SwitchACLPolicySpecApplyConfiguration) WithDefaultAction(value apiv1alpha1.ACLAction) *SwitchACLPolicySpecApplyConfiguration {
	b.DefaultAction = &value
	return b
}

// WithRules adds the given value to the Rules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rules field.
func (b *SwitchACLPolicySpecApplyConfiguration) WithRules(values ...*ACLRuleApplyConfiguration) *SwitchACLPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRules")
		}
		b.Rules = append(b.Rules, *values[i])
	}
	return b
}
