// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchVLANSpecApplyConfiguration represents a declarative configuration of the SwitchVLANSpec type for use
// with apply.
//
// SwitchVLANSpec declares a VLAN and the members that must exist.
type SwitchVLANSpecApplyConfiguration struct {
	// SwitchRef is immutable. Only one CR may claim a switch/VLAN pair.
	SwitchRef *SwitchVLANReferenceApplyConfiguration `json:"switchRef,omitempty"`
	// VLANID is immutable and excludes reserved VLAN IDs.
	VLANID *uint32 `json:"vlanID,omitempty"`
	// ManagementPolicy defaults to observation. Manage also requires both the
	// controller's observe-only gate and the agent's read-only gate to be disabled.
	ManagementPolicy *apiv1alpha1.VLANManagementPolicy `json:"managementPolicy,omitempty"`
	// ReconcilePolicy defaults to Additive. Authoritative owns the entire VLAN
	// membership, pruning omitted members and replacing tagging modes.
	ReconcilePolicy *apiv1alpha1.VLANReconcilePolicy `json:"reconcilePolicy,omitempty"`
	// DeletionPolicy defaults to Orphan. Delete applies only to agent-confirmed
	// ownership by this CR UID, with all authoritative write gates enabled.
	DeletionPolicy *apiv1alpha1.VLANDeletionPolicy `json:"deletionPolicy,omitempty"`
	// AdoptionDigest approves the exact agent snapshot for first takeover of an
	// existing VLAN. Review status.adoptionDigest; newly created VLANs need none.
	AdoptionDigest *string `json:"adoptionDigest,omitempty"`
	// Members are additive by default, or the complete set under Authoritative.
	Members []SwitchVLANMemberApplyConfiguration `json:"members,omitempty"`
}

// SwitchVLANSpecApplyConfiguration constructs a declarative configuration of the SwitchVLANSpec type for use with
// apply.
func SwitchVLANSpec() *SwitchVLANSpecApplyConfiguration {
	return &SwitchVLANSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithSwitchRef(value *SwitchVLANReferenceApplyConfiguration) *SwitchVLANSpecApplyConfiguration {
	b.SwitchRef = value
	return b
}

// WithVLANID sets the VLANID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANID field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithVLANID(value uint32) *SwitchVLANSpecApplyConfiguration {
	b.VLANID = &value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.VLANManagementPolicy) *SwitchVLANSpecApplyConfiguration {
	b.ManagementPolicy = &value
	return b
}

// WithReconcilePolicy sets the ReconcilePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReconcilePolicy field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithReconcilePolicy(value apiv1alpha1.VLANReconcilePolicy) *SwitchVLANSpecApplyConfiguration {
	b.ReconcilePolicy = &value
	return b
}

// WithDeletionPolicy sets the DeletionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionPolicy field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithDeletionPolicy(value apiv1alpha1.VLANDeletionPolicy) *SwitchVLANSpecApplyConfiguration {
	b.DeletionPolicy = &value
	return b
}

// WithAdoptionDigest sets the AdoptionDigest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdoptionDigest field is set to the value of the last call.
func (b *SwitchVLANSpecApplyConfiguration) WithAdoptionDigest(value string) *SwitchVLANSpecApplyConfiguration {
	b.AdoptionDigest = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SwitchVLANSpecApplyConfiguration) WithMembers(values ...*SwitchVLANMemberApplyConfiguration) *SwitchVLANSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}
