// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchSchedulerSpecApplyConfiguration represents a declarative configuration of the SwitchSchedulerSpec type for use
// with apply.
//
// SwitchSchedulerSpec configures scheduling and optional shaping, not policing.
// Rates are bytes/second or packets/second according to meterType; bursts use the same unit.
type SwitchSchedulerSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.QoSPolicyName `json:"name,omitempty"`
	Algorithm                             *string                    `json:"algorithm,omitempty"`
	Weight                                *uint32                    `json:"weight,omitempty"`
	MeterType                             *string                    `json:"meterType,omitempty"`
	// CEL retains the exact integer bound; OpenAPI maximum is float64 and rounds it.
	CommittedRate  *uint64 `json:"committedRate,omitempty"`
	PeakRate       *uint64 `json:"peakRate,omitempty"`
	CommittedBurst *uint64 `json:"committedBurst,omitempty"`
	PeakBurst      *uint64 `json:"peakBurst,omitempty"`
}

// SwitchSchedulerSpecApplyConfiguration constructs a declarative configuration of the SwitchSchedulerSpec type for use with
// apply.
func SwitchSchedulerSpec() *SwitchSchedulerSpecApplyConfiguration {
	return &SwitchSchedulerSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchSchedulerSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchSchedulerSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithName(value apiv1alpha1.QoSPolicyName) *SwitchSchedulerSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithAlgorithm(value string) *SwitchSchedulerSpecApplyConfiguration {
	b.Algorithm = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithWeight(value uint32) *SwitchSchedulerSpecApplyConfiguration {
	b.Weight = &value
	return b
}

// WithMeterType sets the MeterType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeterType field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithMeterType(value string) *SwitchSchedulerSpecApplyConfiguration {
	b.MeterType = &value
	return b
}

// WithCommittedRate sets the CommittedRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommittedRate field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithCommittedRate(value uint64) *SwitchSchedulerSpecApplyConfiguration {
	b.CommittedRate = &value
	return b
}

// WithPeakRate sets the PeakRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeakRate field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithPeakRate(value uint64) *SwitchSchedulerSpecApplyConfiguration {
	b.PeakRate = &value
	return b
}

// WithCommittedBurst sets the CommittedBurst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommittedBurst field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithCommittedBurst(value uint64) *SwitchSchedulerSpecApplyConfiguration {
	b.CommittedBurst = &value
	return b
}

// WithPeakBurst sets the PeakBurst field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeakBurst field is set to the value of the last call.
func (b *SwitchSchedulerSpecApplyConfiguration) WithPeakBurst(value uint64) *SwitchSchedulerSpecApplyConfiguration {
	b.PeakBurst = &value
	return b
}
