// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchEVPNSpecApplyConfiguration represents a declarative configuration of the SwitchEVPNSpec type for use
// with apply.
//
// SwitchEVPNSpec owns global L2 advertisement on one switch.
type SwitchEVPNSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Tunnel                                *apiv1alpha1.RedundancyName                `json:"tunnel,omitempty"`
	MappingRefs                           []NetworkSwitchReferenceApplyConfiguration `json:"mappingRefs,omitempty"`
	AdminState                            *apiv1alpha1.AdminState                    `json:"adminState,omitempty"`
}

// SwitchEVPNSpecApplyConfiguration constructs a declarative configuration of the SwitchEVPNSpec type for use with
// apply.
func SwitchEVPNSpec() *SwitchEVPNSpecApplyConfiguration {
	return &SwitchEVPNSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchEVPNSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchEVPNSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchEVPNSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchEVPNSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithTunnel sets the Tunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tunnel field is set to the value of the last call.
func (b *SwitchEVPNSpecApplyConfiguration) WithTunnel(value apiv1alpha1.RedundancyName) *SwitchEVPNSpecApplyConfiguration {
	b.Tunnel = &value
	return b
}

// WithMappingRefs adds the given value to the MappingRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MappingRefs field.
func (b *SwitchEVPNSpecApplyConfiguration) WithMappingRefs(values ...*NetworkSwitchReferenceApplyConfiguration) *SwitchEVPNSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMappingRefs")
		}
		b.MappingRefs = append(b.MappingRefs, *values[i])
	}
	return b
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *SwitchEVPNSpecApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *SwitchEVPNSpecApplyConfiguration {
	b.AdminState = &value
	return b
}
