// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchVXLANTunnelSpecApplyConfiguration represents a declarative configuration of the SwitchVXLANTunnelSpec type for use
// with apply.
type SwitchVXLANTunnelSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.RedundancyName `json:"name,omitempty"`
	SourceAddress                         *apiv1alpha1.RedundancyIPv4 `json:"sourceAddress,omitempty"`
	EVPNNVO                               *apiv1alpha1.RedundancyName `json:"evpnNVO,omitempty"`
}

// SwitchVXLANTunnelSpecApplyConfiguration constructs a declarative configuration of the SwitchVXLANTunnelSpec type for use with
// apply.
func SwitchVXLANTunnelSpec() *SwitchVXLANTunnelSpecApplyConfiguration {
	return &SwitchVXLANTunnelSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchVXLANTunnelSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchVXLANTunnelSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchVXLANTunnelSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchVXLANTunnelSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchVXLANTunnelSpecApplyConfiguration) WithName(value apiv1alpha1.RedundancyName) *SwitchVXLANTunnelSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithSourceAddress sets the SourceAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceAddress field is set to the value of the last call.
func (b *SwitchVXLANTunnelSpecApplyConfiguration) WithSourceAddress(value apiv1alpha1.RedundancyIPv4) *SwitchVXLANTunnelSpecApplyConfiguration {
	b.SourceAddress = &value
	return b
}

// WithEVPNNVO sets the EVPNNVO field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EVPNNVO field is set to the value of the last call.
func (b *SwitchVXLANTunnelSpecApplyConfiguration) WithEVPNNVO(value apiv1alpha1.RedundancyName) *SwitchVXLANTunnelSpecApplyConfiguration {
	b.EVPNNVO = &value
	return b
}
