// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchFRRMigrationSpecApplyConfiguration represents a declarative configuration of the SwitchFRRMigrationSpec type for use
// with apply.
type SwitchFRRMigrationSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	// Mode selects the target framework for an empty-routing switch. Change mode
	// on the same resource; each transition requires a fresh approved preflight.
	// Traditional explicitly sets false/separated metadata, rather than restoring absent fields.
	Mode *string `json:"mode,omitempty"`
	// ApprovedDigest approves exactly the snapshot published as observed.adoptionDigest.
	// Omit it for read-only preflight. A new Ensure requires a matching digest.
	ApprovedDigest *string `json:"approvedDigest,omitempty"`
}

// SwitchFRRMigrationSpecApplyConfiguration constructs a declarative configuration of the SwitchFRRMigrationSpec type for use with
// apply.
func SwitchFRRMigrationSpec() *SwitchFRRMigrationSpecApplyConfiguration {
	return &SwitchFRRMigrationSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchFRRMigrationSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchFRRMigrationSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchFRRMigrationSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchFRRMigrationSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SwitchFRRMigrationSpecApplyConfiguration) WithMode(value string) *SwitchFRRMigrationSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithApprovedDigest sets the ApprovedDigest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovedDigest field is set to the value of the last call.
func (b *SwitchFRRMigrationSpecApplyConfiguration) WithApprovedDigest(value string) *SwitchFRRMigrationSpecApplyConfiguration {
	b.ApprovedDigest = &value
	return b
}
