// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchMLAGSpecApplyConfiguration represents a declarative configuration of the SwitchMLAGSpec type for use
// with apply.
//
// SwitchMLAGSpec coordinates staged, reciprocal configurations on two switches.
type SwitchMLAGSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	DomainID                              *uint32                                   `json:"domainID,omitempty"`
	PeerSwitchRef                         *NetworkSwitchReferenceApplyConfiguration `json:"peerSwitchRef,omitempty"`
	LocalAddress                          *apiv1alpha1.RedundancyIPv4               `json:"localAddress,omitempty"`
	PeerAddress                           *apiv1alpha1.RedundancyIPv4               `json:"peerAddress,omitempty"`
	PeerLink                              *apiv1alpha1.MLAGPortChannel              `json:"peerLink,omitempty"`
	Members                               []apiv1alpha1.MLAGPortChannel             `json:"members,omitempty"`
	// KeepaliveInterval is in seconds.
	KeepaliveInterval *uint32 `json:"keepaliveInterval,omitempty"`
	// SessionTimeout is in seconds.
	SessionTimeout *uint32 `json:"sessionTimeout,omitempty"`
}

// SwitchMLAGSpecApplyConfiguration constructs a declarative configuration of the SwitchMLAGSpec type for use with
// apply.
func SwitchMLAGSpec() *SwitchMLAGSpecApplyConfiguration {
	return &SwitchMLAGSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchMLAGSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchMLAGSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithDomainID sets the DomainID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainID field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithDomainID(value uint32) *SwitchMLAGSpecApplyConfiguration {
	b.DomainID = &value
	return b
}

// WithPeerSwitchRef sets the PeerSwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerSwitchRef field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithPeerSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchMLAGSpecApplyConfiguration {
	b.PeerSwitchRef = value
	return b
}

// WithLocalAddress sets the LocalAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAddress field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithLocalAddress(value apiv1alpha1.RedundancyIPv4) *SwitchMLAGSpecApplyConfiguration {
	b.LocalAddress = &value
	return b
}

// WithPeerAddress sets the PeerAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerAddress field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithPeerAddress(value apiv1alpha1.RedundancyIPv4) *SwitchMLAGSpecApplyConfiguration {
	b.PeerAddress = &value
	return b
}

// WithPeerLink sets the PeerLink field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerLink field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithPeerLink(value apiv1alpha1.MLAGPortChannel) *SwitchMLAGSpecApplyConfiguration {
	b.PeerLink = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SwitchMLAGSpecApplyConfiguration) WithMembers(values ...apiv1alpha1.MLAGPortChannel) *SwitchMLAGSpecApplyConfiguration {
	for i := range values {
		b.Members = append(b.Members, values[i])
	}
	return b
}

// WithKeepaliveInterval sets the KeepaliveInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepaliveInterval field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithKeepaliveInterval(value uint32) *SwitchMLAGSpecApplyConfiguration {
	b.KeepaliveInterval = &value
	return b
}

// WithSessionTimeout sets the SessionTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionTimeout field is set to the value of the last call.
func (b *SwitchMLAGSpecApplyConfiguration) WithSessionTimeout(value uint32) *SwitchMLAGSpecApplyConfiguration {
	b.SessionTimeout = &value
	return b
}
