// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchBGPSpecApplyConfiguration represents a declarative configuration of the SwitchBGPSpec type for use
// with apply.
type SwitchBGPSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	// Mode selects the existing native backend; it never changes FRR mode.
	// Traditional supports the qualified peerless LeafRouter Loopback0 /32 contract.
	Mode     *string                     `json:"mode,omitempty"`
	VRF      *apiv1alpha1.NetworkVRFName `json:"vrf,omitempty"`
	LocalASN *uint32                     `json:"localASN,omitempty"`
	RouterID *string                     `json:"routerID,omitempty"`
	// Prefixes is an explicit allowlist; empty means no advertisements.
	Prefixes []apiv1alpha1.NetworkPrefix `json:"prefixes,omitempty"`
}

// SwitchBGPSpecApplyConfiguration constructs a declarative configuration of the SwitchBGPSpec type for use with
// apply.
func SwitchBGPSpec() *SwitchBGPSpecApplyConfiguration {
	return &SwitchBGPSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchBGPSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchBGPSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithMode(value string) *SwitchBGPSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithVRF sets the VRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRF field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithVRF(value apiv1alpha1.NetworkVRFName) *SwitchBGPSpecApplyConfiguration {
	b.VRF = &value
	return b
}

// WithLocalASN sets the LocalASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalASN field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithLocalASN(value uint32) *SwitchBGPSpecApplyConfiguration {
	b.LocalASN = &value
	return b
}

// WithRouterID sets the RouterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RouterID field is set to the value of the last call.
func (b *SwitchBGPSpecApplyConfiguration) WithRouterID(value string) *SwitchBGPSpecApplyConfiguration {
	b.RouterID = &value
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *SwitchBGPSpecApplyConfiguration) WithPrefixes(values ...apiv1alpha1.NetworkPrefix) *SwitchBGPSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}
