// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchL3InterfaceSpecApplyConfiguration represents a declarative configuration of the SwitchL3InterfaceSpec type for use
// with apply.
type SwitchL3InterfaceSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *string                     `json:"name,omitempty"`
	VRF                                   *apiv1alpha1.NetworkVRFName `json:"vrf,omitempty"`
	// Addresses retain host bits; removals are not supported.
	Addresses []apiv1alpha1.NetworkInterfaceAddress `json:"addresses,omitempty"`
}

// SwitchL3InterfaceSpecApplyConfiguration constructs a declarative configuration of the SwitchL3InterfaceSpec type for use with
// apply.
func SwitchL3InterfaceSpec() *SwitchL3InterfaceSpecApplyConfiguration {
	return &SwitchL3InterfaceSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchL3InterfaceSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchL3InterfaceSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchL3InterfaceSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchL3InterfaceSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchL3InterfaceSpecApplyConfiguration) WithName(value string) *SwitchL3InterfaceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithVRF sets the VRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRF field is set to the value of the last call.
func (b *SwitchL3InterfaceSpecApplyConfiguration) WithVRF(value apiv1alpha1.NetworkVRFName) *SwitchL3InterfaceSpecApplyConfiguration {
	b.VRF = &value
	return b
}

// WithAddresses adds the given value to the Addresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Addresses field.
func (b *SwitchL3InterfaceSpecApplyConfiguration) WithAddresses(values ...apiv1alpha1.NetworkInterfaceAddress) *SwitchL3InterfaceSpecApplyConfiguration {
	for i := range values {
		b.Addresses = append(b.Addresses, values[i])
	}
	return b
}
