// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
	internal "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SwitchQoSBindingApplyConfiguration represents a declarative configuration of the SwitchQoSBinding type for use
// with apply.
type SwitchQoSBindingApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *SwitchQoSBindingSpecApplyConfiguration  `json:"spec,omitempty"`
	Status                           *NetworkResourceStatusApplyConfiguration `json:"status,omitempty"`
}

// SwitchQoSBinding constructs a declarative configuration of the SwitchQoSBinding type for use with
// apply.
func SwitchQoSBinding(name string) *SwitchQoSBindingApplyConfiguration {
	b := &SwitchQoSBindingApplyConfiguration{}
	b.WithName(name)
	b.WithKind("SwitchQoSBinding")
	b.WithAPIVersion("sonic.networking.metal.ironcore.dev/v1alpha1")
	return b
}

// ExtractSwitchQoSBindingFrom extracts the applied configuration owned by fieldManager from
// switchQoSBinding for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// switchQoSBinding must be a unmodified SwitchQoSBinding API object that was retrieved from the Kubernetes API.
// ExtractSwitchQoSBindingFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSwitchQoSBindingFrom(switchQoSBinding *apiv1alpha1.SwitchQoSBinding, fieldManager string, subresource string) (*SwitchQoSBindingApplyConfiguration, error) {
	b := &SwitchQoSBindingApplyConfiguration{}
	err := managedfields.ExtractInto(switchQoSBinding, internal.Parser().Type("com.github.ironcore-dev.sonic-operator.api.v1alpha1.SwitchQoSBinding"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(switchQoSBinding.Name)

	b.WithKind("SwitchQoSBinding")
	b.WithAPIVersion("sonic.networking.metal.ironcore.dev/v1alpha1")
	return b, nil
}

// ExtractSwitchQoSBinding extracts the applied configuration owned by fieldManager from
// switchQoSBinding. If no managedFields are found in switchQoSBinding for fieldManager, a
// SwitchQoSBindingApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// switchQoSBinding must be a unmodified SwitchQoSBinding API object that was retrieved from the Kubernetes API.
// ExtractSwitchQoSBinding provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSwitchQoSBinding(switchQoSBinding *apiv1alpha1.SwitchQoSBinding, fieldManager string) (*SwitchQoSBindingApplyConfiguration, error) {
	return ExtractSwitchQoSBindingFrom(switchQoSBinding, fieldManager, "")
}

// ExtractSwitchQoSBindingStatus extracts the applied configuration owned by fieldManager from
// switchQoSBinding for the status subresource.
func ExtractSwitchQoSBindingStatus(switchQoSBinding *apiv1alpha1.SwitchQoSBinding, fieldManager string) (*SwitchQoSBindingApplyConfiguration, error) {
	return ExtractSwitchQoSBindingFrom(switchQoSBinding, fieldManager, "status")
}

func (b SwitchQoSBindingApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithKind(value string) *SwitchQoSBindingApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithAPIVersion(value string) *SwitchQoSBindingApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithName(value string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithGenerateName(value string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithNamespace(value string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithUID(value types.UID) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithResourceVersion(value string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithGeneration(value int64) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithCreationTimestamp(value metav1.Time) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SwitchQoSBindingApplyConfiguration) WithLabels(entries map[string]string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SwitchQoSBindingApplyConfiguration) WithAnnotations(entries map[string]string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *SwitchQoSBindingApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *SwitchQoSBindingApplyConfiguration) WithFinalizers(values ...string) *SwitchQoSBindingApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *SwitchQoSBindingApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithSpec(value *SwitchQoSBindingSpecApplyConfiguration) *SwitchQoSBindingApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *SwitchQoSBindingApplyConfiguration) WithStatus(value *NetworkResourceStatusApplyConfiguration) *SwitchQoSBindingApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *SwitchQoSBindingApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *SwitchQoSBindingApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *SwitchQoSBindingApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *SwitchQoSBindingApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
