// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchManagementSpecApplyConfiguration represents a declarative configuration of the SwitchManagementSpec type for use
// with apply.
type SwitchManagementSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Interface                             *string                               `json:"interface,omitempty"`
	Addresses                             []ManagementAddressApplyConfiguration `json:"addresses,omitempty"`
	// MAC overrides only eth0; device/base/front-panel MACs are never changed.
	// Omission leaves the active and boot MAC configuration unowned.
	MAC             *string `json:"mac,omitempty"`
	RollbackSeconds *int    `json:"rollbackSeconds,omitempty"`
}

// SwitchManagementSpecApplyConfiguration constructs a declarative configuration of the SwitchManagementSpec type for use with
// apply.
func SwitchManagementSpec() *SwitchManagementSpecApplyConfiguration {
	return &SwitchManagementSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchManagementSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchManagementSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchManagementSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchManagementSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *SwitchManagementSpecApplyConfiguration) WithInterface(value string) *SwitchManagementSpecApplyConfiguration {
	b.Interface = &value
	return b
}

// WithAddresses adds the given value to the Addresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Addresses field.
func (b *SwitchManagementSpecApplyConfiguration) WithAddresses(values ...*ManagementAddressApplyConfiguration) *SwitchManagementSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAddresses")
		}
		b.Addresses = append(b.Addresses, *values[i])
	}
	return b
}

// WithMAC sets the MAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MAC field is set to the value of the last call.
func (b *SwitchManagementSpecApplyConfiguration) WithMAC(value string) *SwitchManagementSpecApplyConfiguration {
	b.MAC = &value
	return b
}

// WithRollbackSeconds sets the RollbackSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RollbackSeconds field is set to the value of the last call.
func (b *SwitchManagementSpecApplyConfiguration) WithRollbackSeconds(value int) *SwitchManagementSpecApplyConfiguration {
	b.RollbackSeconds = &value
	return b
}
