// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchEVPNPeerSpecApplyConfiguration represents a declarative configuration of the SwitchEVPNPeerSpec type for use
// with apply.
//
// SwitchEVPNPeerSpec owns the EVPN AF of an existing shared BGP neighbor.
type SwitchEVPNPeerSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	// Role distinguishes local VTEP participation from spine transit.
	Role *string `json:"role,omitempty"`
	// Transit peers use explicit RT sets without local mapping references.
	ImportRouteTargets []apiv1alpha1.RouteIdentifier `json:"importRouteTargets,omitempty"`
	ExportRouteTargets []apiv1alpha1.RouteIdentifier `json:"exportRouteTargets,omitempty"`
	VRF                *apiv1alpha1.NetworkVRFName   `json:"vrf,omitempty"`
	Address            *apiv1alpha1.NetworkIP        `json:"address,omitempty"`
	RemoteASN          *uint32                       `json:"remoteASN,omitempty"`
	LocalAddress       *apiv1alpha1.NetworkIP        `json:"localAddress,omitempty"`
	// AdminState controls the EVPN address family, not shared neighbor fields.
	AdminState *apiv1alpha1.AdminState `json:"adminState,omitempty"`
	// MappingRefs selects the local VLAN/VNI policies permitted on this peer.
	// Existing Down-only peers may omit this field; activation requires it.
	MappingRefs []NetworkSwitchReferenceApplyConfiguration `json:"mappingRefs,omitempty"`
}

// SwitchEVPNPeerSpecApplyConfiguration constructs a declarative configuration of the SwitchEVPNPeerSpec type for use with
// apply.
func SwitchEVPNPeerSpec() *SwitchEVPNPeerSpecApplyConfiguration {
	return &SwitchEVPNPeerSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchEVPNPeerSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchEVPNPeerSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithRole(value string) *SwitchEVPNPeerSpecApplyConfiguration {
	b.Role = &value
	return b
}

// WithImportRouteTargets adds the given value to the ImportRouteTargets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImportRouteTargets field.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithImportRouteTargets(values ...apiv1alpha1.RouteIdentifier) *SwitchEVPNPeerSpecApplyConfiguration {
	for i := range values {
		b.ImportRouteTargets = append(b.ImportRouteTargets, values[i])
	}
	return b
}

// WithExportRouteTargets adds the given value to the ExportRouteTargets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExportRouteTargets field.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithExportRouteTargets(values ...apiv1alpha1.RouteIdentifier) *SwitchEVPNPeerSpecApplyConfiguration {
	for i := range values {
		b.ExportRouteTargets = append(b.ExportRouteTargets, values[i])
	}
	return b
}

// WithVRF sets the VRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRF field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithVRF(value apiv1alpha1.NetworkVRFName) *SwitchEVPNPeerSpecApplyConfiguration {
	b.VRF = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithAddress(value apiv1alpha1.NetworkIP) *SwitchEVPNPeerSpecApplyConfiguration {
	b.Address = &value
	return b
}

// WithRemoteASN sets the RemoteASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteASN field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithRemoteASN(value uint32) *SwitchEVPNPeerSpecApplyConfiguration {
	b.RemoteASN = &value
	return b
}

// WithLocalAddress sets the LocalAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAddress field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithLocalAddress(value apiv1alpha1.NetworkIP) *SwitchEVPNPeerSpecApplyConfiguration {
	b.LocalAddress = &value
	return b
}

// WithAdminState sets the AdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminState field is set to the value of the last call.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithAdminState(value apiv1alpha1.AdminState) *SwitchEVPNPeerSpecApplyConfiguration {
	b.AdminState = &value
	return b
}

// WithMappingRefs adds the given value to the MappingRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MappingRefs field.
func (b *SwitchEVPNPeerSpecApplyConfiguration) WithMappingRefs(values ...*NetworkSwitchReferenceApplyConfiguration) *SwitchEVPNPeerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMappingRefs")
		}
		b.MappingRefs = append(b.MappingRefs, *values[i])
	}
	return b
}
