// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchDHCPRelaySpecApplyConfiguration represents a declarative configuration of the SwitchDHCPRelaySpec type for use
// with apply.
type SwitchDHCPRelaySpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	VLANID                                *uint32                     `json:"vlanID,omitempty"`
	VRF                                   *apiv1alpha1.NetworkVRFName `json:"vrf,omitempty"`
	IPv4Servers                           []string                    `json:"ipv4Servers,omitempty"`
	IPv6Servers                           []string                    `json:"ipv6Servers,omitempty"`
}

// SwitchDHCPRelaySpecApplyConfiguration constructs a declarative configuration of the SwitchDHCPRelaySpec type for use with
// apply.
func SwitchDHCPRelaySpec() *SwitchDHCPRelaySpecApplyConfiguration {
	return &SwitchDHCPRelaySpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchDHCPRelaySpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchDHCPRelaySpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithVLANID sets the VLANID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANID field is set to the value of the last call.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithVLANID(value uint32) *SwitchDHCPRelaySpecApplyConfiguration {
	b.VLANID = &value
	return b
}

// WithVRF sets the VRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRF field is set to the value of the last call.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithVRF(value apiv1alpha1.NetworkVRFName) *SwitchDHCPRelaySpecApplyConfiguration {
	b.VRF = &value
	return b
}

// WithIPv4Servers adds the given value to the IPv4Servers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPv4Servers field.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithIPv4Servers(values ...string) *SwitchDHCPRelaySpecApplyConfiguration {
	for i := range values {
		b.IPv4Servers = append(b.IPv4Servers, values[i])
	}
	return b
}

// WithIPv6Servers adds the given value to the IPv6Servers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IPv6Servers field.
func (b *SwitchDHCPRelaySpecApplyConfiguration) WithIPv6Servers(values ...string) *SwitchDHCPRelaySpecApplyConfiguration {
	for i := range values {
		b.IPv6Servers = append(b.IPv6Servers, values[i])
	}
	return b
}
