// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchPortBreakoutReferenceApplyConfiguration represents a declarative configuration of the SwitchPortBreakoutReference type for use
// with apply.
//
// SwitchPortBreakoutReference identifies a cluster-scoped Switch.
type SwitchPortBreakoutReferenceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// SwitchPortBreakoutReferenceApplyConfiguration constructs a declarative configuration of the SwitchPortBreakoutReference type for use with
// apply.
func SwitchPortBreakoutReference() *SwitchPortBreakoutReferenceApplyConfiguration {
	return &SwitchPortBreakoutReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchPortBreakoutReferenceApplyConfiguration) WithName(value string) *SwitchPortBreakoutReferenceApplyConfiguration {
	b.Name = &value
	return b
}
