// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchPortBreakoutSpecApplyConfiguration represents a declarative configuration of the SwitchPortBreakoutSpec type for use
// with apply.
//
// SwitchPortBreakoutSpec requests an exact platform-supported port layout.
type SwitchPortBreakoutSpecApplyConfiguration struct {
	// SwitchRef is immutable. Target UID and endpoint are bound before writes.
	SwitchRef *SwitchPortBreakoutReferenceApplyConfiguration `json:"switchRef,omitempty"`
	// Port is the immutable canonical native parent, not an alias or handle.
	Port *string `json:"port,omitempty"`
	// Mode must exactly match one of status.supportedModes.
	Mode *string `json:"mode,omitempty"`
	// Manage also requires both manager and agent write gates.
	ManagementPolicy *apiv1alpha1.BreakoutManagementPolicy `json:"managementPolicy,omitempty"`
	// ChildAdminState seeds only newly created device children. Existing
	// SwitchInterface desired state and unaffected device attributes are retained.
	ChildAdminState *apiv1alpha1.AdminState `json:"childAdminState,omitempty"`
}

// SwitchPortBreakoutSpecApplyConfiguration constructs a declarative configuration of the SwitchPortBreakoutSpec type for use with
// apply.
func SwitchPortBreakoutSpec() *SwitchPortBreakoutSpecApplyConfiguration {
	return &SwitchPortBreakoutSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchPortBreakoutSpecApplyConfiguration) WithSwitchRef(value *SwitchPortBreakoutReferenceApplyConfiguration) *SwitchPortBreakoutSpecApplyConfiguration {
	b.SwitchRef = value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *SwitchPortBreakoutSpecApplyConfiguration) WithPort(value string) *SwitchPortBreakoutSpecApplyConfiguration {
	b.Port = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SwitchPortBreakoutSpecApplyConfiguration) WithMode(value string) *SwitchPortBreakoutSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchPortBreakoutSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.BreakoutManagementPolicy) *SwitchPortBreakoutSpecApplyConfiguration {
	b.ManagementPolicy = &value
	return b
}

// WithChildAdminState sets the ChildAdminState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChildAdminState field is set to the value of the last call.
func (b *SwitchPortBreakoutSpecApplyConfiguration) WithChildAdminState(value apiv1alpha1.AdminState) *SwitchPortBreakoutSpecApplyConfiguration {
	b.ChildAdminState = &value
	return b
}
