// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
	internal "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SwitchVLANApplyConfiguration represents a declarative configuration of the SwitchVLAN type for use
// with apply.
//
// SwitchVLAN manages Layer-2 VLAN configuration. Additive is the safe default;
// authoritative ownership requires explicit gates and a cleanup finalizer.
type SwitchVLANApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *SwitchVLANSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *SwitchVLANStatusApplyConfiguration `json:"status,omitempty"`
}

// SwitchVLAN constructs a declarative configuration of the SwitchVLAN type for use with
// apply.
func SwitchVLAN(name string) *SwitchVLANApplyConfiguration {
	b := &SwitchVLANApplyConfiguration{}
	b.WithName(name)
	b.WithKind("SwitchVLAN")
	b.WithAPIVersion("sonic.networking.metal.ironcore.dev/v1alpha1")
	return b
}

// ExtractSwitchVLANFrom extracts the applied configuration owned by fieldManager from
// switchVLAN for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// switchVLAN must be a unmodified SwitchVLAN API object that was retrieved from the Kubernetes API.
// ExtractSwitchVLANFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSwitchVLANFrom(switchVLAN *apiv1alpha1.SwitchVLAN, fieldManager string, subresource string) (*SwitchVLANApplyConfiguration, error) {
	b := &SwitchVLANApplyConfiguration{}
	err := managedfields.ExtractInto(switchVLAN, internal.Parser().Type("com.github.ironcore-dev.sonic-operator.api.v1alpha1.SwitchVLAN"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(switchVLAN.Name)

	b.WithKind("SwitchVLAN")
	b.WithAPIVersion("sonic.networking.metal.ironcore.dev/v1alpha1")
	return b, nil
}

// ExtractSwitchVLAN extracts the applied configuration owned by fieldManager from
// switchVLAN. If no managedFields are found in switchVLAN for fieldManager, a
// SwitchVLANApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// switchVLAN must be a unmodified SwitchVLAN API object that was retrieved from the Kubernetes API.
// ExtractSwitchVLAN provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractSwitchVLAN(switchVLAN *apiv1alpha1.SwitchVLAN, fieldManager string) (*SwitchVLANApplyConfiguration, error) {
	return ExtractSwitchVLANFrom(switchVLAN, fieldManager, "")
}

// ExtractSwitchVLANStatus extracts the applied configuration owned by fieldManager from
// switchVLAN for the status subresource.
func ExtractSwitchVLANStatus(switchVLAN *apiv1alpha1.SwitchVLAN, fieldManager string) (*SwitchVLANApplyConfiguration, error) {
	return ExtractSwitchVLANFrom(switchVLAN, fieldManager, "status")
}

func (b SwitchVLANApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithKind(value string) *SwitchVLANApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithAPIVersion(value string) *SwitchVLANApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithName(value string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithGenerateName(value string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithNamespace(value string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithUID(value types.UID) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithResourceVersion(value string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithGeneration(value int64) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithCreationTimestamp(value metav1.Time) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *SwitchVLANApplyConfiguration) WithLabels(entries map[string]string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *SwitchVLANApplyConfiguration) WithAnnotations(entries map[string]string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *SwitchVLANApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *SwitchVLANApplyConfiguration) WithFinalizers(values ...string) *SwitchVLANApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *SwitchVLANApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithSpec(value *SwitchVLANSpecApplyConfiguration) *SwitchVLANApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *SwitchVLANApplyConfiguration) WithStatus(value *SwitchVLANStatusApplyConfiguration) *SwitchVLANApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *SwitchVLANApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *SwitchVLANApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *SwitchVLANApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *SwitchVLANApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
