// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SwitchVLANReferenceApplyConfiguration represents a declarative configuration of the SwitchVLANReference type for use
// with apply.
//
// SwitchVLANReference identifies the cluster-scoped Switch to configure.
type SwitchVLANReferenceApplyConfiguration struct {
	// Name is the name of an existing Switch.
	Name *string `json:"name,omitempty"`
}

// SwitchVLANReferenceApplyConfiguration constructs a declarative configuration of the SwitchVLANReference type for use with
// apply.
func SwitchVLANReference() *SwitchVLANReferenceApplyConfiguration {
	return &SwitchVLANReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchVLANReferenceApplyConfiguration) WithName(value string) *SwitchVLANReferenceApplyConfiguration {
	b.Name = &value
	return b
}
