// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
)

// SwitchBufferPoolSpecApplyConfiguration represents a declarative configuration of the SwitchBufferPoolSpec type for use
// with apply.
//
// SwitchBufferPoolSpec owns explicitly declared BUFFER_POOL fields.
type SwitchBufferPoolSpecApplyConfiguration struct {
	NetworkResourceSpecApplyConfiguration `json:",inline"`
	Name                                  *apiv1alpha1.BufferName `json:"name,omitempty"`
	Type                                  *string                 `json:"type,omitempty"`
	Mode                                  *string                 `json:"mode,omitempty"`
	// Size is the pool size in bytes. Actual capacity requires native qualification.
	// CEL retains the exact integer bound; OpenAPI maximum is float64 and rounds it.
	Size *uint64 `json:"size,omitempty"`
	// Xoff is shared headroom in bytes.
	Xoff *uint64 `json:"xoff,omitempty"`
}

// SwitchBufferPoolSpecApplyConfiguration constructs a declarative configuration of the SwitchBufferPoolSpec type for use with
// apply.
func SwitchBufferPoolSpec() *SwitchBufferPoolSpecApplyConfiguration {
	return &SwitchBufferPoolSpecApplyConfiguration{}
}

// WithSwitchRef sets the SwitchRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SwitchRef field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithSwitchRef(value *NetworkSwitchReferenceApplyConfiguration) *SwitchBufferPoolSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.SwitchRef = value
	return b
}

// WithManagementPolicy sets the ManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagementPolicy field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithManagementPolicy(value apiv1alpha1.NetworkManagementPolicy) *SwitchBufferPoolSpecApplyConfiguration {
	b.NetworkResourceSpecApplyConfiguration.ManagementPolicy = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithName(value apiv1alpha1.BufferName) *SwitchBufferPoolSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithType(value string) *SwitchBufferPoolSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithMode(value string) *SwitchBufferPoolSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithSize(value uint64) *SwitchBufferPoolSpecApplyConfiguration {
	b.Size = &value
	return b
}

// WithXoff sets the Xoff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Xoff field is set to the value of the last call.
func (b *SwitchBufferPoolSpecApplyConfiguration) WithXoff(value uint64) *SwitchBufferPoolSpecApplyConfiguration {
	b.Xoff = &value
	return b
}
