// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SwitchVLANStatusApplyConfiguration represents a declarative configuration of the SwitchVLANStatus type for use
// with apply.
//
// SwitchVLANStatus reports configuration, not dataplane or forwarding health.
type SwitchVLANStatusApplyConfiguration struct {
	// ObservedGeneration is the generation last attempted by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// AdoptionDigest is the latest agent snapshot digest for explicit review.
	AdoptionDigest *string `json:"adoptionDigest,omitempty"`
	// OwnerID is the last confirmed agent owner UID, never a grant of ownership.
	OwnerID *string `json:"ownerID,omitempty"`
	// TargetIdentity binds ownership to the Switch UID and explicit endpoint.
	TargetIdentity *string `json:"targetIdentity,omitempty"`
	// RuntimeVerified confirms CONFIG_DB only, not ASIC state or forwarding.
	RuntimeVerified *bool `json:"runtimeVerified,omitempty"`
	// PersistenceVerified confirms the agent's durable configuration save.
	PersistenceVerified *bool `json:"persistenceVerified,omitempty"`
	// Exists is unset when existence could not be determined in this attempt.
	Exists *bool `json:"exists,omitempty"`
	// Members is the latest successful observation, including unmanaged members.
	Members []SwitchVLANObservedMemberApplyConfiguration `json:"members,omitempty"`
	// Ready and Synced are true only after confirming the requested configuration.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// SwitchVLANStatusApplyConfiguration constructs a declarative configuration of the SwitchVLANStatus type for use with
// apply.
func SwitchVLANStatus() *SwitchVLANStatusApplyConfiguration {
	return &SwitchVLANStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithObservedGeneration(value int64) *SwitchVLANStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithAdoptionDigest sets the AdoptionDigest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdoptionDigest field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithAdoptionDigest(value string) *SwitchVLANStatusApplyConfiguration {
	b.AdoptionDigest = &value
	return b
}

// WithOwnerID sets the OwnerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerID field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithOwnerID(value string) *SwitchVLANStatusApplyConfiguration {
	b.OwnerID = &value
	return b
}

// WithTargetIdentity sets the TargetIdentity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetIdentity field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithTargetIdentity(value string) *SwitchVLANStatusApplyConfiguration {
	b.TargetIdentity = &value
	return b
}

// WithRuntimeVerified sets the RuntimeVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeVerified field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithRuntimeVerified(value bool) *SwitchVLANStatusApplyConfiguration {
	b.RuntimeVerified = &value
	return b
}

// WithPersistenceVerified sets the PersistenceVerified field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistenceVerified field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithPersistenceVerified(value bool) *SwitchVLANStatusApplyConfiguration {
	b.PersistenceVerified = &value
	return b
}

// WithExists sets the Exists field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exists field is set to the value of the last call.
func (b *SwitchVLANStatusApplyConfiguration) WithExists(value bool) *SwitchVLANStatusApplyConfiguration {
	b.Exists = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *SwitchVLANStatusApplyConfiguration) WithMembers(values ...*SwitchVLANObservedMemberApplyConfiguration) *SwitchVLANStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SwitchVLANStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SwitchVLANStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
