// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SystemSNMPApplyConfiguration represents a declarative configuration of the SystemSNMP type for use
// with apply.
type SystemSNMPApplyConfiguration struct {
	Location *string `json:"location,omitempty"`
	// Empty Contact leaves the native contact input unowned.
	Contact *string `json:"contact,omitempty"`
	// CommunitySecretRef supplies the sole read-only community. Omission declares
	// no communities. Plaintext is never allowed in this resource.
	CommunitySecretRef *HostSecretKeyReferenceApplyConfiguration `json:"communitySecretRef,omitempty"`
}

// SystemSNMPApplyConfiguration constructs a declarative configuration of the SystemSNMP type for use with
// apply.
func SystemSNMP() *SystemSNMPApplyConfiguration {
	return &SystemSNMPApplyConfiguration{}
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *SystemSNMPApplyConfiguration) WithLocation(value string) *SystemSNMPApplyConfiguration {
	b.Location = &value
	return b
}

// WithContact sets the Contact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Contact field is set to the value of the last call.
func (b *SystemSNMPApplyConfiguration) WithContact(value string) *SystemSNMPApplyConfiguration {
	b.Contact = &value
	return b
}

// WithCommunitySecretRef sets the CommunitySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommunitySecretRef field is set to the value of the last call.
func (b *SystemSNMPApplyConfiguration) WithCommunitySecretRef(value *HostSecretKeyReferenceApplyConfiguration) *SystemSNMPApplyConfiguration {
	b.CommunitySecretRef = value
	return b
}
