// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.2
// source: pkg/agent/proto/artifact.proto

package switchagentproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactService_GetCapabilities_FullMethodName = "/artifact.ArtifactService/GetCapabilities"
	ArtifactService_PrepareContent_FullMethodName  = "/artifact.ArtifactService/PrepareContent"
	ArtifactService_UploadContent_FullMethodName   = "/artifact.ArtifactService/UploadContent"
	ArtifactService_Bootstrap_FullMethodName       = "/artifact.ArtifactService/Bootstrap"
	ArtifactService_Observe_FullMethodName         = "/artifact.ArtifactService/Observe"
	ArtifactService_Stage_FullMethodName           = "/artifact.ArtifactService/Stage"
	ArtifactService_Confirm_FullMethodName         = "/artifact.ArtifactService/Confirm"
)

// ArtifactServiceClient is the client API for ArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactServiceClient interface {
	GetCapabilities(ctx context.Context, in *ArtifactCapabilitiesRequest, opts ...grpc.CallOption) (*ArtifactCapabilitiesResponse, error)
	PrepareContent(ctx context.Context, in *ArtifactPrepareRequest, opts ...grpc.CallOption) (*ArtifactPrepareResponse, error)
	UploadContent(ctx context.Context, in *ArtifactChunkRequest, opts ...grpc.CallOption) (*ArtifactChunkResponse, error)
	Bootstrap(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	Observe(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	Stage(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
	Confirm(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error)
}

type artifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactServiceClient(cc grpc.ClientConnInterface) ArtifactServiceClient {
	return &artifactServiceClient{cc}
}

func (c *artifactServiceClient) GetCapabilities(ctx context.Context, in *ArtifactCapabilitiesRequest, opts ...grpc.CallOption) (*ArtifactCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ArtifactService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) PrepareContent(ctx context.Context, in *ArtifactPrepareRequest, opts ...grpc.CallOption) (*ArtifactPrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactPrepareResponse)
	err := c.cc.Invoke(ctx, ArtifactService_PrepareContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) UploadContent(ctx context.Context, in *ArtifactChunkRequest, opts ...grpc.CallOption) (*ArtifactChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactChunkResponse)
	err := c.cc.Invoke(ctx, ArtifactService_UploadContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) Bootstrap(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) Observe(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) Stage(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_Stage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) Confirm(ctx context.Context, in *ArtifactRequest, opts ...grpc.CallOption) (*ArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactServiceServer is the server API for ArtifactService service.
// All implementations must embed UnimplementedArtifactServiceServer
// for forward compatibility.
type ArtifactServiceServer interface {
	GetCapabilities(context.Context, *ArtifactCapabilitiesRequest) (*ArtifactCapabilitiesResponse, error)
	PrepareContent(context.Context, *ArtifactPrepareRequest) (*ArtifactPrepareResponse, error)
	UploadContent(context.Context, *ArtifactChunkRequest) (*ArtifactChunkResponse, error)
	Bootstrap(context.Context, *ArtifactRequest) (*ArtifactResponse, error)
	Observe(context.Context, *ArtifactRequest) (*ArtifactResponse, error)
	Stage(context.Context, *ArtifactRequest) (*ArtifactResponse, error)
	Confirm(context.Context, *ArtifactRequest) (*ArtifactResponse, error)
	mustEmbedUnimplementedArtifactServiceServer()
}

// UnimplementedArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactServiceServer struct{}

func (UnimplementedArtifactServiceServer) GetCapabilities(context.Context, *ArtifactCapabilitiesRequest) (*ArtifactCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedArtifactServiceServer) PrepareContent(context.Context, *ArtifactPrepareRequest) (*ArtifactPrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareContent not implemented")
}
func (UnimplementedArtifactServiceServer) UploadContent(context.Context, *ArtifactChunkRequest) (*ArtifactChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadContent not implemented")
}
func (UnimplementedArtifactServiceServer) Bootstrap(context.Context, *ArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedArtifactServiceServer) Observe(context.Context, *ArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedArtifactServiceServer) Stage(context.Context, *ArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stage not implemented")
}
func (UnimplementedArtifactServiceServer) Confirm(context.Context, *ArtifactRequest) (*ArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedArtifactServiceServer) mustEmbedUnimplementedArtifactServiceServer() {}
func (UnimplementedArtifactServiceServer) testEmbeddedByValue()                         {}

// UnsafeArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactServiceServer will
// result in compilation errors.
type UnsafeArtifactServiceServer interface {
	mustEmbedUnimplementedArtifactServiceServer()
}

func RegisterArtifactServiceServer(s grpc.ServiceRegistrar, srv ArtifactServiceServer) {
	// If the following call panics, it indicates UnimplementedArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactService_ServiceDesc, srv)
}

func _ArtifactService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).GetCapabilities(ctx, req.(*ArtifactCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_PrepareContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactPrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).PrepareContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_PrepareContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).PrepareContent(ctx, req.(*ArtifactPrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_UploadContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).UploadContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_UploadContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).UploadContent(ctx, req.(*ArtifactChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).Bootstrap(ctx, req.(*ArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).Observe(ctx, req.(*ArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_Stage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).Stage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_Stage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).Stage(ctx, req.(*ArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).Confirm(ctx, req.(*ArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactService_ServiceDesc is the grpc.ServiceDesc for ArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artifact.ArtifactService",
	HandlerType: (*ArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _ArtifactService_GetCapabilities_Handler,
		},
		{
			MethodName: "PrepareContent",
			Handler:    _ArtifactService_PrepareContent_Handler,
		},
		{
			MethodName: "UploadContent",
			Handler:    _ArtifactService_UploadContent_Handler,
		},
		{
			MethodName: "Bootstrap",
			Handler:    _ArtifactService_Bootstrap_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _ArtifactService_Observe_Handler,
		},
		{
			MethodName: "Stage",
			Handler:    _ArtifactService_Stage_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _ArtifactService_Confirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agent/proto/artifact.proto",
}
