// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: pkg/agent/proto/artifact.proto

package switchagentproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bundle JSON is decoded with unknown-field rejection into the bounded artifact
// model. It cannot contain destinations, commands or activation scripts.
type ArtifactRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BundleJson        []byte                 `protobuf:"bytes,1,opt,name=bundle_json,json=bundleJson,proto3" json:"bundle_json,omitempty"`
	ConfirmationToken string                 `protobuf:"bytes,2,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	ContentSession    string                 `protobuf:"bytes,3,opt,name=content_session,json=contentSession,proto3" json:"content_session,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ArtifactRequest) Reset() {
	*x = ArtifactRequest{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRequest) ProtoMessage() {}

func (x *ArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRequest.ProtoReflect.Descriptor instead.
func (*ArtifactRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRequest) GetBundleJson() []byte {
	if x != nil {
		return x.BundleJson
	}
	return nil
}

func (x *ArtifactRequest) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

func (x *ArtifactRequest) GetContentSession() string {
	if x != nil {
		return x.ContentSession
	}
	return ""
}

type ArtifactBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactBlob) Reset() {
	*x = ArtifactBlob{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactBlob) ProtoMessage() {}

func (x *ArtifactBlob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactBlob.ProtoReflect.Descriptor instead.
func (*ArtifactBlob) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactBlob) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactBlob) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ArtifactOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactOffset) Reset() {
	*x = ArtifactOffset{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactOffset) ProtoMessage() {}

func (x *ArtifactOffset) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactOffset.ProtoReflect.Descriptor instead.
func (*ArtifactOffset) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactOffset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactOffset) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ArtifactPrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleJson    []byte                 `protobuf:"bytes,1,opt,name=bundle_json,json=bundleJson,proto3" json:"bundle_json,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Blobs         []*ArtifactBlob        `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactPrepareRequest) Reset() {
	*x = ArtifactPrepareRequest{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactPrepareRequest) ProtoMessage() {}

func (x *ArtifactPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactPrepareRequest.ProtoReflect.Descriptor instead.
func (*ArtifactPrepareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactPrepareRequest) GetBundleJson() []byte {
	if x != nil {
		return x.BundleJson
	}
	return nil
}

func (x *ArtifactPrepareRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ArtifactPrepareRequest) GetBlobs() []*ArtifactBlob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

type ArtifactPrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Offsets       []*ArtifactOffset      `protobuf:"bytes,2,rep,name=offsets,proto3" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactPrepareResponse) Reset() {
	*x = ArtifactPrepareResponse{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactPrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactPrepareResponse) ProtoMessage() {}

func (x *ArtifactPrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactPrepareResponse.ProtoReflect.Descriptor instead.
func (*ArtifactPrepareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactPrepareResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ArtifactPrepareResponse) GetOffsets() []*ArtifactOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type ArtifactChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunkRequest) Reset() {
	*x = ArtifactChunkRequest{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunkRequest) ProtoMessage() {}

func (x *ArtifactChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunkRequest.ProtoReflect.Descriptor instead.
func (*ArtifactChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ArtifactChunkRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ArtifactChunkRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactChunkRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ArtifactChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunkResponse) Reset() {
	*x = ArtifactChunkResponse{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunkResponse) ProtoMessage() {}

func (x *ArtifactChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunkResponse.ProtoReflect.Descriptor instead.
func (*ArtifactChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactChunkResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ArtifactResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationVerified bool                   `protobuf:"varint,1,opt,name=configuration_verified,json=configurationVerified,proto3" json:"configuration_verified,omitempty"`
	RuntimeVerified       bool                   `protobuf:"varint,2,opt,name=runtime_verified,json=runtimeVerified,proto3" json:"runtime_verified,omitempty"`
	PersistenceVerified   bool                   `protobuf:"varint,3,opt,name=persistence_verified,json=persistenceVerified,proto3" json:"persistence_verified,omitempty"`
	RecoveryPhase         string                 `protobuf:"bytes,4,opt,name=recovery_phase,json=recoveryPhase,proto3" json:"recovery_phase,omitempty"`
	ConfirmationToken     string                 `protobuf:"bytes,5,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"`
	Identity              string                 `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"`
	Reason                string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ArtifactResponse) Reset() {
	*x = ArtifactResponse{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactResponse) ProtoMessage() {}

func (x *ArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactResponse.ProtoReflect.Descriptor instead.
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactResponse) GetConfigurationVerified() bool {
	if x != nil {
		return x.ConfigurationVerified
	}
	return false
}

func (x *ArtifactResponse) GetRuntimeVerified() bool {
	if x != nil {
		return x.RuntimeVerified
	}
	return false
}

func (x *ArtifactResponse) GetPersistenceVerified() bool {
	if x != nil {
		return x.PersistenceVerified
	}
	return false
}

func (x *ArtifactResponse) GetRecoveryPhase() string {
	if x != nil {
		return x.RecoveryPhase
	}
	return ""
}

func (x *ArtifactResponse) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

func (x *ArtifactResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ArtifactResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ArtifactCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactCapabilitiesRequest) Reset() {
	*x = ArtifactCapabilitiesRequest{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCapabilitiesRequest) ProtoMessage() {}

func (x *ArtifactCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ArtifactCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{8}
}

type ArtifactCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCommit  string                 `protobuf:"bytes,1,opt,name=source_commit,json=sourceCommit,proto3" json:"source_commit,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactCapabilitiesResponse) Reset() {
	*x = ArtifactCapabilitiesResponse{}
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCapabilitiesResponse) ProtoMessage() {}

func (x *ArtifactCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_proto_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ArtifactCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_proto_artifact_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactCapabilitiesResponse) GetSourceCommit() string {
	if x != nil {
		return x.SourceCommit
	}
	return ""
}

func (x *ArtifactCapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_pkg_agent_proto_artifact_proto protoreflect.FileDescriptor

const file_pkg_agent_proto_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/agent/proto/artifact.proto\x12\bartifact\"\x8a\x01\n" +
	"\x0fArtifactRequest\x12\x1f\n" +
	"\vbundle_json\x18\x01 \x01(\fR\n" +
	"bundleJson\x12-\n" +
	"\x12confirmation_token\x18\x02 \x01(\tR\x11confirmationToken\x12'\n" +
	"\x0fcontent_session\x18\x03 \x01(\tR\x0econtentSession\":\n" +
	"\fArtifactBlob\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"@\n" +
	"\x0eArtifactOffset\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"\x85\x01\n" +
	"\x16ArtifactPrepareRequest\x12\x1f\n" +
	"\vbundle_json\x18\x01 \x01(\fR\n" +
	"bundleJson\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12,\n" +
	"\x05blobs\x18\x03 \x03(\v2\x16.artifact.ArtifactBlobR\x05blobs\"g\n" +
	"\x17ArtifactPrepareResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x122\n" +
	"\aoffsets\x18\x02 \x03(\v2\x18.artifact.ArtifactOffsetR\aoffsets\"t\n" +
	"\x14ArtifactChunkRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"/\n" +
	"\x15ArtifactChunkResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\"\xb1\x02\n" +
	"\x10ArtifactResponse\x125\n" +
	"\x16configuration_verified\x18\x01 \x01(\bR\x15configurationVerified\x12)\n" +
	"\x10runtime_verified\x18\x02 \x01(\bR\x0fruntimeVerified\x121\n" +
	"\x14persistence_verified\x18\x03 \x01(\bR\x13persistenceVerified\x12%\n" +
	"\x0erecovery_phase\x18\x04 \x01(\tR\rrecoveryPhase\x12-\n" +
	"\x12confirmation_token\x18\x05 \x01(\tR\x11confirmationToken\x12\x1a\n" +
	"\bidentity\x18\x06 \x01(\tR\bidentity\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\x1d\n" +
	"\x1bArtifactCapabilitiesRequest\"g\n" +
	"\x1cArtifactCapabilitiesResponse\x12#\n" +
	"\rsource_commit\x18\x01 \x01(\tR\fsourceCommit\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities2\xa4\x04\n" +
	"\x0fArtifactService\x12`\n" +
	"\x0fGetCapabilities\x12%.artifact.ArtifactCapabilitiesRequest\x1a&.artifact.ArtifactCapabilitiesResponse\x12U\n" +
	"\x0ePrepareContent\x12 .artifact.ArtifactPrepareRequest\x1a!.artifact.ArtifactPrepareResponse\x12P\n" +
	"\rUploadContent\x12\x1e.artifact.ArtifactChunkRequest\x1a\x1f.artifact.ArtifactChunkResponse\x12B\n" +
	"\tBootstrap\x12\x19.artifact.ArtifactRequest\x1a\x1a.artifact.ArtifactResponse\x12@\n" +
	"\aObserve\x12\x19.artifact.ArtifactRequest\x1a\x1a.artifact.ArtifactResponse\x12>\n" +
	"\x05Stage\x12\x19.artifact.ArtifactRequest\x1a\x1a.artifact.ArtifactResponse\x12@\n" +
	"\aConfirm\x12\x19.artifact.ArtifactRequest\x1a\x1a.artifact.ArtifactResponseBIZGgithub.com/ironcore-dev/sonic-operator/pkg/agent/proto;switchagentprotob\x06proto3"

var (
	file_pkg_agent_proto_artifact_proto_rawDescOnce sync.Once
	file_pkg_agent_proto_artifact_proto_rawDescData []byte
)

func file_pkg_agent_proto_artifact_proto_rawDescGZIP() []byte {
	file_pkg_agent_proto_artifact_proto_rawDescOnce.Do(func() {
		file_pkg_agent_proto_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_proto_artifact_proto_rawDesc), len(file_pkg_agent_proto_artifact_proto_rawDesc)))
	})
	return file_pkg_agent_proto_artifact_proto_rawDescData
}

var file_pkg_agent_proto_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_agent_proto_artifact_proto_goTypes = []any{
	(*ArtifactRequest)(nil),              // 0: artifact.ArtifactRequest
	(*ArtifactBlob)(nil),                 // 1: artifact.ArtifactBlob
	(*ArtifactOffset)(nil),               // 2: artifact.ArtifactOffset
	(*ArtifactPrepareRequest)(nil),       // 3: artifact.ArtifactPrepareRequest
	(*ArtifactPrepareResponse)(nil),      // 4: artifact.ArtifactPrepareResponse
	(*ArtifactChunkRequest)(nil),         // 5: artifact.ArtifactChunkRequest
	(*ArtifactChunkResponse)(nil),        // 6: artifact.ArtifactChunkResponse
	(*ArtifactResponse)(nil),             // 7: artifact.ArtifactResponse
	(*ArtifactCapabilitiesRequest)(nil),  // 8: artifact.ArtifactCapabilitiesRequest
	(*ArtifactCapabilitiesResponse)(nil), // 9: artifact.ArtifactCapabilitiesResponse
}
var file_pkg_agent_proto_artifact_proto_depIdxs = []int32{
	1, // 0: artifact.ArtifactPrepareRequest.blobs:type_name -> artifact.ArtifactBlob
	2, // 1: artifact.ArtifactPrepareResponse.offsets:type_name -> artifact.ArtifactOffset
	8, // 2: artifact.ArtifactService.GetCapabilities:input_type -> artifact.ArtifactCapabilitiesRequest
	3, // 3: artifact.ArtifactService.PrepareContent:input_type -> artifact.ArtifactPrepareRequest
	5, // 4: artifact.ArtifactService.UploadContent:input_type -> artifact.ArtifactChunkRequest
	0, // 5: artifact.ArtifactService.Bootstrap:input_type -> artifact.ArtifactRequest
	0, // 6: artifact.ArtifactService.Observe:input_type -> artifact.ArtifactRequest
	0, // 7: artifact.ArtifactService.Stage:input_type -> artifact.ArtifactRequest
	0, // 8: artifact.ArtifactService.Confirm:input_type -> artifact.ArtifactRequest
	9, // 9: artifact.ArtifactService.GetCapabilities:output_type -> artifact.ArtifactCapabilitiesResponse
	4, // 10: artifact.ArtifactService.PrepareContent:output_type -> artifact.ArtifactPrepareResponse
	6, // 11: artifact.ArtifactService.UploadContent:output_type -> artifact.ArtifactChunkResponse
	7, // 12: artifact.ArtifactService.Bootstrap:output_type -> artifact.ArtifactResponse
	7, // 13: artifact.ArtifactService.Observe:output_type -> artifact.ArtifactResponse
	7, // 14: artifact.ArtifactService.Stage:output_type -> artifact.ArtifactResponse
	7, // 15: artifact.ArtifactService.Confirm:output_type -> artifact.ArtifactResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_agent_proto_artifact_proto_init() }
func file_pkg_agent_proto_artifact_proto_init() {
	if File_pkg_agent_proto_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_proto_artifact_proto_rawDesc), len(file_pkg_agent_proto_artifact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_proto_artifact_proto_goTypes,
		DependencyIndexes: file_pkg_agent_proto_artifact_proto_depIdxs,
		MessageInfos:      file_pkg_agent_proto_artifact_proto_msgTypes,
	}.Build()
	File_pkg_agent_proto_artifact_proto = out.File
	file_pkg_agent_proto_artifact_proto_goTypes = nil
	file_pkg_agent_proto_artifact_proto_depIdxs = nil
}
