// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1"
	apiv1alpha1 "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/api/v1alpha1"
	internal "github.com/ironcore-dev/sonic-operator/api/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=sonic.networking.metal.ironcore.dev, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ACLRule"):
		return &apiv1alpha1.ACLRuleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactAgentOptions"):
		return &apiv1alpha1.ArtifactAgentOptionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactBootstrapSpec"):
		return &apiv1alpha1.ArtifactBootstrapSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactContentRef"):
		return &apiv1alpha1.ArtifactContentRefApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactFile"):
		return &apiv1alpha1.ArtifactFileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactHostRecoverySpec"):
		return &apiv1alpha1.ArtifactHostRecoverySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ArtifactMACHookSpec"):
		return &apiv1alpha1.ArtifactMACHookSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostResourceStatus"):
		return &apiv1alpha1.HostResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostSecretKeyReference"):
		return &apiv1alpha1.HostSecretKeyReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ManagementAddress"):
		return &apiv1alpha1.ManagementAddressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Neighbor"):
		return &apiv1alpha1.NeighborApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceSpec"):
		return &apiv1alpha1.NetworkResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkResourceStatus"):
		return &apiv1alpha1.NetworkResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NetworkSwitchReference"):
		return &apiv1alpha1.NetworkSwitchReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("QoSMapEntry"):
		return &apiv1alpha1.QoSMapEntryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("QoSQueueBinding"):
		return &apiv1alpha1.QoSQueueBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("StaticRouteNextHop"):
		return &apiv1alpha1.StaticRouteNextHopApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchACLBinding"):
		return &apiv1alpha1.SwitchACLBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchACLBindingSpec"):
		return &apiv1alpha1.SwitchACLBindingSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchACLPolicy"):
		return &apiv1alpha1.SwitchACLPolicyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchACLPolicySpec"):
		return &apiv1alpha1.SwitchACLPolicySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchArtifact"):
		return &apiv1alpha1.SwitchArtifactApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchArtifactSpec"):
		return &apiv1alpha1.SwitchArtifactSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchArtifactStatus"):
		return &apiv1alpha1.SwitchArtifactStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGP"):
		return &apiv1alpha1.SwitchBGPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGPPeer"):
		return &apiv1alpha1.SwitchBGPPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGPPeerSpec"):
		return &apiv1alpha1.SwitchBGPPeerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchBGPSpec"):
		return &apiv1alpha1.SwitchBGPSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchCredentials"):
		return &apiv1alpha1.SwitchCredentialsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchDHCPRelay"):
		return &apiv1alpha1.SwitchDHCPRelayApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchDHCPRelaySpec"):
		return &apiv1alpha1.SwitchDHCPRelaySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchEVPN"):
		return &apiv1alpha1.SwitchEVPNApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchEVPNPeer"):
		return &apiv1alpha1.SwitchEVPNPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchEVPNPeerSpec"):
		return &apiv1alpha1.SwitchEVPNPeerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchEVPNSpec"):
		return &apiv1alpha1.SwitchEVPNSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchFRRMigration"):
		return &apiv1alpha1.SwitchFRRMigrationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchFRRMigrationSpec"):
		return &apiv1alpha1.SwitchFRRMigrationSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterface"):
		return &apiv1alpha1.SwitchInterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterfaceSpec"):
		return &apiv1alpha1.SwitchInterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchInterfaceStatus"):
		return &apiv1alpha1.SwitchInterfaceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchL3Interface"):
		return &apiv1alpha1.SwitchL3InterfaceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchL3InterfaceSpec"):
		return &apiv1alpha1.SwitchL3InterfaceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchManagement"):
		return &apiv1alpha1.SwitchManagementApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchManagementSpec"):
		return &apiv1alpha1.SwitchManagementSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchMLAG"):
		return &apiv1alpha1.SwitchMLAGApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchMLAGSpec"):
		return &apiv1alpha1.SwitchMLAGSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortBreakout"):
		return &apiv1alpha1.SwitchPortBreakoutApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortBreakoutChild"):
		return &apiv1alpha1.SwitchPortBreakoutChildApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortBreakoutReference"):
		return &apiv1alpha1.SwitchPortBreakoutReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortBreakoutSpec"):
		return &apiv1alpha1.SwitchPortBreakoutSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortBreakoutStatus"):
		return &apiv1alpha1.SwitchPortBreakoutStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortChannel"):
		return &apiv1alpha1.SwitchPortChannelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchPortChannelSpec"):
		return &apiv1alpha1.SwitchPortChannelSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchQoSBinding"):
		return &apiv1alpha1.SwitchQoSBindingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchQoSBindingSpec"):
		return &apiv1alpha1.SwitchQoSBindingSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchQoSMap"):
		return &apiv1alpha1.SwitchQoSMapApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchQoSMapSpec"):
		return &apiv1alpha1.SwitchQoSMapSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchScheduler"):
		return &apiv1alpha1.SwitchSchedulerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchSchedulerSpec"):
		return &apiv1alpha1.SwitchSchedulerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchStaticRoute"):
		return &apiv1alpha1.SwitchStaticRouteApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchStaticRouteSpec"):
		return &apiv1alpha1.SwitchStaticRouteSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchSystem"):
		return &apiv1alpha1.SwitchSystemApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchSystemSpec"):
		return &apiv1alpha1.SwitchSystemSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLAN"):
		return &apiv1alpha1.SwitchVLANApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANMember"):
		return &apiv1alpha1.SwitchVLANMemberApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANObservedMember"):
		return &apiv1alpha1.SwitchVLANObservedMemberApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANReference"):
		return &apiv1alpha1.SwitchVLANReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANSpec"):
		return &apiv1alpha1.SwitchVLANSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANStatus"):
		return &apiv1alpha1.SwitchVLANStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANVNI"):
		return &apiv1alpha1.SwitchVLANVNIApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVLANVNISpec"):
		return &apiv1alpha1.SwitchVLANVNISpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVRF"):
		return &apiv1alpha1.SwitchVRFApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVRFSpec"):
		return &apiv1alpha1.SwitchVRFSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVXLANTunnel"):
		return &apiv1alpha1.SwitchVXLANTunnelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SwitchVXLANTunnelSpec"):
		return &apiv1alpha1.SwitchVXLANTunnelSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SystemNTP"):
		return &apiv1alpha1.SystemNTPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SystemSNMP"):
		return &apiv1alpha1.SystemSNMPApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
