// SPDX-License-Identifier: Apache-2.0
package artifact

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"flag"
	"fmt"
	"io"
	"strings"

	"github.com/ironcore-dev/sonic-operator/internal/agent/releaseinfo"
)

type ReleaseBuild = releaseinfo.Info

func ValidateAgentRelease(policy Policy, binarySHA256 string) error {
	if !shaPattern.MatchString(binarySHA256) || len(policy.AgentBuilds) == 0 || len(policy.AgentBuilds) > 16 {
		return fmt.Errorf("accepted agent release required")
	}
	for hash, build := range policy.AgentBuilds {
		if !shaPattern.MatchString(hash) || releaseinfo.Validate(build) != nil {
			return fmt.Errorf("invalid accepted agent release set")
		}
	}
	if _, ok := policy.AgentBuilds[binarySHA256]; !ok {
		return fmt.Errorf("agent binary is outside accepted release set")
	}
	return nil
}

func agentRecoverySlot(slot string) bool {
	switch slot {
	case "AgentBinary", "AgentUnit", "AgentCertificate", "AgentKey", "AgentCA":
		return true
	}
	return false
}

// Only exact generated units can be protected for rollback. Parsing finite
// typed flags and comparing regenerated bytes excludes drop-ins/shell commands.
func releaseAgentOptions(unit []byte) (AgentOptions, error) {
	var o AgentOptions
	f := flag.NewFlagSet("agent", flag.ContinueOnError)
	f.SetOutput(io.Discard)
	f.StringVar(&o.BindAddress, "bind-address", "", "")
	f.IntVar(&o.Port, "port", 0, "")
	for name, p := range map[string]*bool{"read-only": &o.ReadOnly, "allow-authoritative-vlans": &o.VLANAuthority, "allow-breakout": &o.Breakout, "allow-network-config": &o.Network, "allow-frr-migration": &o.FRRMigration, "allow-traffic-policy": &o.TrafficPolicy, "allow-redundancy": &o.Redundancy, "allow-artifacts": &o.Artifacts, "allow-host-config": &o.HostConfig} {
		f.BoolVar(p, name, false, "")
	}
	var hostDir string
	f.StringVar(&hostDir, "host-journal-dir", "", "")
	for _, name := range []string{"tls-cert-file", "tls-key-file", "tls-client-ca-file", "vlan-authority-journal-dir", "breakout-journal-dir", "network-journal-dir"} {
		f.String(name, "", "")
	}
	f.Bool("artifact-reservation-v1", false, "")
	var args []string
	for _, line := range strings.Split(string(unit), "\n") {
		if strings.HasPrefix(line, "ExecStart=/usr/local/sbin/sonic-operator-agent ") {
			args = strings.Fields(strings.TrimPrefix(line, "ExecStart=/usr/local/sbin/sonic-operator-agent "))
		}
	}
	if len(args) == 0 || f.Parse(args) != nil || f.NArg() != 0 {
		return o, fmt.Errorf("unqualified recovery agent unit")
	}
	o.HostGuard = hostDir != ""
	generated, err := AgentUnit(o)
	if err != nil || !bytes.Equal(generated, unit) || !o.HostGuard || !o.Artifacts || o.ReadOnly {
		return o, fmt.Errorf("recovery unit drops integrated host/artifact guard")
	}
	return o, nil
}

func validateAgentPlans(policy Policy, plans []stagedPlan) error {
	agent := map[string]stagedPlan{}
	for _, p := range plans {
		if agentRecoverySlot(p.file.Slot) {
			agent[p.file.Slot] = p
		}
	}
	if len(agent) == 0 {
		return nil
	}
	if len(agent) != 5 {
		return fmt.Errorf("complete declared agent recovery set required")
	}
	for _, p := range agent {
		if !p.record.Existed || len(p.previous) == 0 {
			return fmt.Errorf("protected old agent input required")
		}
		_, mode, _ := Destination(p.file.Slot)
		if p.file.Slot == "AgentUnit" {
			mode = 0644
		}
		if p.record.PreviousMode != mode {
			return fmt.Errorf("protected old agent input mode is not restorable")
		}
	}
	b := agent["AgentBinary"]
	if ValidateAgentRelease(policy, Digest(b.file.Data)) != nil || ValidateAgentRelease(policy, Digest(b.previous)) != nil {
		return fmt.Errorf("candidate or fallback is outside accepted release floor")
	}
	next, err := releaseAgentOptions(agent["AgentUnit"].file.Data)
	if err != nil {
		return err
	}
	old, err := releaseAgentOptions(agent["AgentUnit"].previous)
	if err != nil {
		return err
	}
	if next.BindAddress != old.BindAddress || next.Port != old.Port {
		return fmt.Errorf("agent endpoint rebind requires independent migration")
	}
	if _, err := tls.X509KeyPair(agent["AgentCertificate"].previous, agent["AgentKey"].previous); err != nil {
		return fmt.Errorf("protected old TLS pair is not restorable")
	}
	if !x509.NewCertPool().AppendCertsFromPEM(agent["AgentCA"].previous) {
		return fmt.Errorf("protected old TLS trust is not restorable")
	}
	return nil
}

// Recheck protected bytes on restart and before any recovery write. Historical
// journals remain readable, but an incomplete/below-floor agent set stays fenced.
func (e *Engine) validateProtectedAgent(j *journal, which string, files []savedFile) error {
	var plans []stagedPlan
	for i, f := range files {
		if !agentRecoverySlot(f.Slot) {
			continue
		}
		data, _, err := e.read(e.storage(j, which, i))
		hash := f.Hash
		mode := f.Mode
		if which == "old" {
			hash = f.PreviousHash
			mode = f.PreviousMode
		}
		if err != nil || Digest(data) != hash {
			return fmt.Errorf("protected agent recovery identity unavailable")
		}
		plans = append(plans, stagedPlan{file: File{Slot: f.Slot, Data: data, SHA256: hash}, record: savedFile{Existed: true, PreviousMode: mode}, previous: data})
	}
	return validateAgentPlans(e.Policy, plans)
}
