// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/agent/hostproto/host.proto

package hostproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Closed typed JSON is decoded with duplicate/unknown-field rejection. It is
// private mTLS input only; responses never contain desired/observed credentials.
type HostRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationJson []byte                 `protobuf:"bytes,1,opt,name=configuration_json,json=configurationJson,proto3" json:"configuration_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_hostproto_host_proto_rawDescGZIP(), []int{0}
}

func (x *HostRequest) GetConfigurationJson() []byte {
	if x != nil {
		return x.ConfigurationJson
	}
	return nil
}

type HostConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Transaction   string                 `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Challenge     string                 `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostConfirmation) Reset() {
	*x = HostConfirmation{}
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostConfirmation) ProtoMessage() {}

func (x *HostConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostConfirmation.ProtoReflect.Descriptor instead.
func (*HostConfirmation) Descriptor() ([]byte, []int) {
	return file_internal_agent_hostproto_host_proto_rawDescGZIP(), []int{1}
}

func (x *HostConfirmation) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HostConfirmation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HostConfirmation) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *HostConfirmation) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type HostResult struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationVerified bool                   `protobuf:"varint,1,opt,name=configuration_verified,json=configurationVerified,proto3" json:"configuration_verified,omitempty"`
	RuntimeVerified       bool                   `protobuf:"varint,2,opt,name=runtime_verified,json=runtimeVerified,proto3" json:"runtime_verified,omitempty"`
	PersistenceVerified   bool                   `protobuf:"varint,3,opt,name=persistence_verified,json=persistenceVerified,proto3" json:"persistence_verified,omitempty"`
	GatewayVerified       bool                   `protobuf:"varint,4,opt,name=gateway_verified,json=gatewayVerified,proto3" json:"gateway_verified,omitempty"`
	Recovery              string                 `protobuf:"bytes,5,opt,name=recovery,proto3" json:"recovery,omitempty"`
	Transaction           string                 `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Challenge             string                 `protobuf:"bytes,7,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Owner                 string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HostResult) Reset() {
	*x = HostResult{}
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostResult) ProtoMessage() {}

func (x *HostResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_hostproto_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostResult.ProtoReflect.Descriptor instead.
func (*HostResult) Descriptor() ([]byte, []int) {
	return file_internal_agent_hostproto_host_proto_rawDescGZIP(), []int{2}
}

func (x *HostResult) GetConfigurationVerified() bool {
	if x != nil {
		return x.ConfigurationVerified
	}
	return false
}

func (x *HostResult) GetRuntimeVerified() bool {
	if x != nil {
		return x.RuntimeVerified
	}
	return false
}

func (x *HostResult) GetPersistenceVerified() bool {
	if x != nil {
		return x.PersistenceVerified
	}
	return false
}

func (x *HostResult) GetGatewayVerified() bool {
	if x != nil {
		return x.GatewayVerified
	}
	return false
}

func (x *HostResult) GetRecovery() string {
	if x != nil {
		return x.Recovery
	}
	return ""
}

func (x *HostResult) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *HostResult) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *HostResult) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_internal_agent_hostproto_host_proto protoreflect.FileDescriptor

const file_internal_agent_hostproto_host_proto_rawDesc = "" +
	"\n" +
	"#internal/agent/hostproto/host.proto\x12\x13switchagent.host.v1\"<\n" +
	"\vHostRequest\x12-\n" +
	"\x12configuration_json\x18\x01 \x01(\fR\x11configurationJson\"\x80\x01\n" +
	"\x10HostConfirmation\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12 \n" +
	"\vtransaction\x18\x03 \x01(\tR\vtransaction\x12\x1c\n" +
	"\tchallenge\x18\x04 \x01(\tR\tchallenge\"\xbe\x02\n" +
	"\n" +
	"HostResult\x125\n" +
	"\x16configuration_verified\x18\x01 \x01(\bR\x15configurationVerified\x12)\n" +
	"\x10runtime_verified\x18\x02 \x01(\bR\x0fruntimeVerified\x121\n" +
	"\x14persistence_verified\x18\x03 \x01(\bR\x13persistenceVerified\x12)\n" +
	"\x10gateway_verified\x18\x04 \x01(\bR\x0fgatewayVerified\x12\x1a\n" +
	"\brecovery\x18\x05 \x01(\tR\brecovery\x12 \n" +
	"\vtransaction\x18\x06 \x01(\tR\vtransaction\x12\x1c\n" +
	"\tchallenge\x18\a \x01(\tR\tchallenge\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner2\xf7\x01\n" +
	"\vHostService\x12H\n" +
	"\x03Get\x12 .switchagent.host.v1.HostRequest\x1a\x1f.switchagent.host.v1.HostResult\x12K\n" +
	"\x06Ensure\x12 .switchagent.host.v1.HostRequest\x1a\x1f.switchagent.host.v1.HostResult\x12Q\n" +
	"\aConfirm\x12%.switchagent.host.v1.HostConfirmation\x1a\x1f.switchagent.host.v1.HostResultBAZ?github.com/ironcore-dev/sonic-operator/internal/agent/hostprotob\x06proto3"

var (
	file_internal_agent_hostproto_host_proto_rawDescOnce sync.Once
	file_internal_agent_hostproto_host_proto_rawDescData []byte
)

func file_internal_agent_hostproto_host_proto_rawDescGZIP() []byte {
	file_internal_agent_hostproto_host_proto_rawDescOnce.Do(func() {
		file_internal_agent_hostproto_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_hostproto_host_proto_rawDesc), len(file_internal_agent_hostproto_host_proto_rawDesc)))
	})
	return file_internal_agent_hostproto_host_proto_rawDescData
}

var file_internal_agent_hostproto_host_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_agent_hostproto_host_proto_goTypes = []any{
	(*HostRequest)(nil),      // 0: switchagent.host.v1.HostRequest
	(*HostConfirmation)(nil), // 1: switchagent.host.v1.HostConfirmation
	(*HostResult)(nil),       // 2: switchagent.host.v1.HostResult
}
var file_internal_agent_hostproto_host_proto_depIdxs = []int32{
	0, // 0: switchagent.host.v1.HostService.Get:input_type -> switchagent.host.v1.HostRequest
	0, // 1: switchagent.host.v1.HostService.Ensure:input_type -> switchagent.host.v1.HostRequest
	1, // 2: switchagent.host.v1.HostService.Confirm:input_type -> switchagent.host.v1.HostConfirmation
	2, // 3: switchagent.host.v1.HostService.Get:output_type -> switchagent.host.v1.HostResult
	2, // 4: switchagent.host.v1.HostService.Ensure:output_type -> switchagent.host.v1.HostResult
	2, // 5: switchagent.host.v1.HostService.Confirm:output_type -> switchagent.host.v1.HostResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_agent_hostproto_host_proto_init() }
func file_internal_agent_hostproto_host_proto_init() {
	if File_internal_agent_hostproto_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_hostproto_host_proto_rawDesc), len(file_internal_agent_hostproto_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agent_hostproto_host_proto_goTypes,
		DependencyIndexes: file_internal_agent_hostproto_host_proto_depIdxs,
		MessageInfos:      file_internal_agent_hostproto_host_proto_msgTypes,
	}.Build()
	File_internal_agent_hostproto_host_proto = out.File
	file_internal_agent_hostproto_host_proto_goTypes = nil
	file_internal_agent_hostproto_host_proto_depIdxs = nil
}
