// SPDX-License-Identifier: Apache-2.0
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ArtifactContentRef pins an immutable object, including its UID, so deleting
// and recreating an identically named source cannot replace approved bytes.
type ArtifactContentRef struct {
	// +kubebuilder:validation:Enum=ConfigMap;Secret
	Kind string `json:"kind"`
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`
	// +kubebuilder:validation:MinLength=1
	UID string `json:"uid"`
	// +kubebuilder:validation:MinLength=1
	Key string `json:"key"`
}

// +kubebuilder:validation:XValidation:rule="self.slot in ['AgentKey', 'AgentCertificate', 'AgentCA'] ? self.chunks.all(c, c.kind == 'Secret') : self.chunks.all(c, c.kind == 'ConfigMap')",message="certificate slots require Secret references; software slots require ConfigMap references"
type ArtifactFile struct {
	// +kubebuilder:validation:Enum=AgentBinary;AgentCertificate;AgentKey;AgentCA;PlatformJSON;HWSKUJSON;PortConfig;SAIProfile;BroadcomConfig;PlatformWheel;PlatformInit;PlatformChassis;PlatformSFP;PlatformEEPROM;PlatformPSU;PlatformFan;PlatformThermal;PlatformAPI;PlatformComponent;PlatformFanDrawer
	Slot string `json:"slot"`
	// SHA256 is over the concatenation of the referenced chunks in order.
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	SHA256 string `json:"sha256"`
	// Chunks permit binaries larger than the Kubernetes single-object limit.
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	Chunks []ArtifactContentRef `json:"chunks"`
}

// ArtifactAgentOptions is rendered into a fixed unit; unit text and arbitrary
// flags cannot be supplied as artifact content.
type ArtifactAgentOptions struct {
	HostConfig  bool   `json:"hostConfig,omitempty"`
	HostGuard   bool   `json:"hostGuard,omitempty"`
	BindAddress string `json:"bindAddress"`
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port          int  `json:"port"`
	ReadOnly      bool `json:"readOnly,omitempty"`
	VLANAuthority bool `json:"vlanAuthority,omitempty"`
	Breakout      bool `json:"breakout,omitempty"`
	Network       bool `json:"network,omitempty"`
	FRRMigration  bool `json:"frrMigration,omitempty"`
	TrafficPolicy bool `json:"trafficPolicy,omitempty"`
	Redundancy    bool `json:"redundancy,omitempty"`
	Artifacts     bool `json:"artifacts,omitempty"`
}

// ArtifactBootstrapSpec declares the immutable recovery baseline. The main
// agent independently enforces it so recovery never depends on replacing itself.
// Changes are governed by SwitchArtifactSpec.BootstrapMigrationFrom.
// +kubebuilder:validation:XValidation:rule="self.supervisorChunks.all(c, c.kind == 'ConfigMap') && self.policyRef.kind == 'ConfigMap'",message="bootstrap inputs require immutable ConfigMap references"
type ArtifactBootstrapSpec struct {
	// +optional
	HostRecovery *ArtifactHostRecoverySpec `json:"hostRecovery,omitempty"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	SupervisorSHA256 string `json:"supervisorSHA256"`
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	SupervisorChunks []ArtifactContentRef `json:"supervisorChunks"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	PolicySHA256 string             `json:"policySHA256"`
	PolicyRef    ArtifactContentRef `json:"policyRef"`
	// SHA of the fixed unit generated by the agent protocol version.
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	UnitSHA256 string `json:"unitSHA256"`
}

// ArtifactHostRecoverySpec selects the finite FleetHostV1 suite. No executable
// arguments, destination paths or generated unit text are accepted.
// +kubebuilder:validation:XValidation:rule="self.binaryChunks.all(c, c.kind == 'ConfigMap') && self.profileRef.kind == 'ConfigMap'",message="host inputs require immutable ConfigMap references"
type ArtifactHostRecoverySpec struct {
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	BinarySHA256 string `json:"binarySHA256"`
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=256
	BinaryChunks []ArtifactContentRef `json:"binaryChunks"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	ProfileSHA256 string             `json:"profileSHA256"`
	ProfileRef    ArtifactContentRef `json:"profileRef"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	ServiceSHA256 string `json:"serviceSHA256"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	TimerSHA256 string `json:"timerSHA256"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	ConfigSHA256 string `json:"configSHA256"`
	// +kubebuilder:validation:Enum=FleetHostV1
	JournalLayout string `json:"journalLayout"`
	// +kubebuilder:validation:MaxItems=2
	// +listType=map
	// +listMapKey=kind
	// +optional
	MACHooks []ArtifactMACHookSpec `json:"macHooks,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.sourceHookRef.kind == 'ConfigMap' && self.helperRef.kind == 'ConfigMap'",message="MAC imports require immutable ConfigMap references"
type ArtifactMACHookSpec struct {
	// dc-management-only and set-management are deprecated legacy names for the
	// same helpers, accepted for hooks installed by earlier releases.
	// +kubebuilder:validation:Enum=management-mac-python;management-mac-shell;dc-management-only;set-management
	Kind string `json:"kind"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	SourceHookSHA256 string             `json:"sourceHookSHA256"`
	SourceHookRef    ArtifactContentRef `json:"sourceHookRef"`
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	HelperSHA256 string             `json:"helperSHA256"`
	HelperRef    ArtifactContentRef `json:"helperRef"`
}

// +kubebuilder:validation:XValidation:rule="!has(self.managementPolicy) || self.managementPolicy != 'Manage' || has(self.bootstrap)",message="Manage requires a declared immutable bootstrap baseline"
// +kubebuilder:validation:XValidation:rule="!has(self.agent) || !has(self.agent.hostConfig) || !self.agent.hostConfig || (has(self.bootstrap) && has(self.bootstrap.hostRecovery) && has(self.agent.hostGuard) && self.agent.hostGuard)",message="HostConfig requires a complete host baseline and HostGuard"
// +kubebuilder:validation:XValidation:rule="!has(self.bootstrap) || !has(self.bootstrap.hostRecovery) || (has(self.agent) && has(self.agent.hostGuard) && self.agent.hostGuard)",message="host bootstrap requires retained HostGuard"
// +kubebuilder:validation:XValidation:rule="!has(oldSelf.bootstrap) || (has(self.bootstrap) && (self.bootstrap == oldSelf.bootstrap || (has(self.bootstrapMigrationFrom) && self.bootstrapMigrationFrom == oldSelf.bootstrap.policySHA256 && self.bootstrap.unitSHA256 == oldSelf.bootstrap.unitSHA256 && has(self.bootstrap.hostRecovery) == has(oldSelf.bootstrap.hostRecovery) && (!has(self.bootstrap.hostRecovery) || self.bootstrap.hostRecovery == oldSelf.bootstrap.hostRecovery))))",message="bootstrap baseline is immutable; supervisor and policy may only change with bootstrapMigrationFrom set to the replaced policySHA256, and hostRecovery and unitSHA256 unchanged"
type SwitchArtifactSpec struct {
	// +optional
	Bootstrap *ArtifactBootstrapSpec `json:"bootstrap,omitempty"`
	// BootstrapMigrationFrom explicitly approves replacing the bootstrap
	// supervisor and policy. It must equal the policySHA256 being replaced;
	// hostRecovery and unitSHA256 must stay unchanged. The switch still rejects
	// the new identity until its recorded bootstrap owner is migrated.
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{64}$`
	// +optional
	BootstrapMigrationFrom string `json:"bootstrapMigrationFrom,omitempty"`
	// Retire the existing legacy site hook only after full site content health and
	// protected persistence are proven by the confirming controller connection.
	// +optional
	RetireLegacyHook bool `json:"retireLegacyHook,omitempty"`
	// +kubebuilder:default=AgentRestart
	// +kubebuilder:validation:Enum=AgentRestart;PlatformNextBoot
	Activation string `json:"activation,omitempty"`
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="switchName is immutable"
	SwitchName string `json:"switchName"`
	// Baseline must match the independently installed supervisor policy.
	// +kubebuilder:validation:MinLength=1
	Baseline string `json:"baseline"`
	// +kubebuilder:default=Observe
	// +kubebuilder:validation:Enum=Observe;Manage
	ManagementPolicy string `json:"managementPolicy,omitempty"`
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=64
	// +listType=map
	// +listMapKey=slot
	Files []ArtifactFile `json:"files"`
	// +optional
	Agent *ArtifactAgentOptions `json:"agent,omitempty"`
}
type SwitchArtifactStatus struct {
	RecoveryReason        string `json:"recoveryReason,omitempty"`
	ObservedGeneration    int64  `json:"observedGeneration,omitempty"`
	ConfigurationVerified bool   `json:"configurationVerified,omitempty"`
	RuntimeVerified       bool   `json:"runtimeVerified,omitempty"`
	PersistenceVerified   bool   `json:"persistenceVerified,omitempty"`
	RecoveryPhase         string `json:"recoveryPhase,omitempty"`
	// Target binds UID, endpoint and credential reference across retries.
	Target   string `json:"target,omitempty"`
	Identity string `json:"identity,omitempty"`
	// ConfirmedGeneration is the generation whose declaration the switch last
	// confirmed. A later generation with identical content (for example only a
	// managementPolicy change) is converged without staging again.
	ConfirmedGeneration int64 `json:"confirmedGeneration,omitempty"`
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Switch",type=string,JSONPath=`.spec.switchName`
// +kubebuilder:printcolumn:name="Baseline",type=string,JSONPath=`.spec.baseline`
// +kubebuilder:printcolumn:name="Policy",type=string,JSONPath=`.spec.managementPolicy`
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.recoveryPhase`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].reason`,priority=1
// +kubebuilder:printcolumn:name="Activation",type=string,JSONPath=`.spec.activation`,priority=1
// +kubebuilder:printcolumn:name="Generation",type=integer,JSONPath=`.metadata.generation`,priority=1
// +kubebuilder:printcolumn:name="Confirmed",type=integer,JSONPath=`.status.confirmedGeneration`,priority=1
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
type SwitchArtifact struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SwitchArtifactSpec `json:"spec"`
	// +optional
	Status SwitchArtifactStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type SwitchArtifactList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SwitchArtifact `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(GroupVersion, &SwitchArtifact{}, &SwitchArtifactList{})
		return nil
	})
}
