// SPDX-License-Identifier: Apache-2.0

package sonic

import (
	"context"
	"encoding/json"
	"errors"
	"maps"
	"strings"
	"testing"
)

// sairedis base object types occupy VID bits 55..48. RIDs are opaque SDK IDs;
// they deliberately do not use the VID encoding or equal the VID in fixtures.
const (
	aclTestTable          = "oid:0x7000000000011"
	aclTestCounterDefault = "oid:0x9000000000021"
	aclTestCounterWeb     = "oid:0x9000000000022"
	aclTestEntryDefault   = "oid:0x8000000000031"
	aclTestEntryWeb       = "oid:0x8000000000032"
	aclTestPort           = "oid:0x1000000000041"
	aclTestGroup          = "oid:0xb000000000051"
	aclTestMember         = "oid:0xc000000000061"
	aclTestLAG            = "oid:0x2000000000071"
)

// Literal native evidence follows sonic-swss 202511 tests/test_acl.py and
// tests/dvslib/dvs_acl.py; it is deliberately not generated by aclEntryDesired.
func aclNativeFixture() map[string]vlanChangeDB {
	return map[string]vlanChangeDB{
		"STATE_DB": {
			"ACL_STAGE_CAPABILITY_TABLE|INGRESS": {"action_list": "PACKET_ACTION,REDIRECT_ACTION", "is_action_list_mandatory": "false", "supported_L3V4V6": "false"},
			"ACL_TABLE_TABLE|EDGE":               {"status": "Active"},
			"ACL_RULE_TABLE|EDGE|DEFAULT":        {"status": "Active"},
			"ACL_RULE_TABLE|EDGE|WEB":            {"status": "Active"},
			"PORT_TABLE|Ethernet0":               {"state": "ok"},
		},
		"COUNTERS_DB": {
			"CRM:ACL_STATS:INGRESS:PORT":        {"crm_stats_acl_table_available": "3"},
			"CRM:ACL_STATS:INGRESS:LAG":         {"crm_stats_acl_table_available": "3"},
			"ACL_COUNTER_RULE_MAP":              {"EDGE:DEFAULT": aclTestCounterDefault, "EDGE:WEB": aclTestCounterWeb, "UNRELATED:R": "oid:0x9000000000099"},
			"COUNTERS:" + aclTestCounterDefault: {"SAI_ACL_COUNTER_ATTR_PACKETS": "0", "SAI_ACL_COUNTER_ATTR_BYTES": "0"},
			"COUNTERS:" + aclTestCounterWeb:     {"SAI_ACL_COUNTER_ATTR_PACKETS": "18446744073709551615", "SAI_ACL_COUNTER_ATTR_BYTES": "42"},
			"COUNTERS_PORT_NAME_MAP":            {"Ethernet0": aclTestPort},
		},
		"ASIC_DB": {
			"VIDTORID":                      {aclTestTable: "oid:0x101", aclTestCounterDefault: "oid:0x102", aclTestCounterWeb: "oid:0x103", aclTestEntryDefault: "oid:0x104", aclTestEntryWeb: "oid:0x105", aclTestPort: "oid:0x106"},
			aclASIC + "PORT:" + aclTestPort: {"SAI_PORT_ATTR_ADMIN_STATE": "true"},
			aclASIC + "ACL_TABLE:" + aclTestTable: {
				"SAI_ACL_TABLE_ATTR_ACL_STAGE":         "SAI_ACL_STAGE_INGRESS",
				"SAI_ACL_TABLE_ATTR_FIELD_ACL_IP_TYPE": "true",
				"SAI_ACL_TABLE_ATTR_FIELD_SRC_IP":      "true",
				"SAI_ACL_TABLE_ATTR_FIELD_IP_PROTOCOL": "true",
				"SAI_ACL_TABLE_ATTR_FIELD_L4_DST_PORT": "true",
			},
			aclASIC + "ACL_COUNTER:" + aclTestCounterDefault: {"SAI_ACL_COUNTER_ATTR_TABLE_ID": aclTestTable, "SAI_ACL_COUNTER_ATTR_ENABLE_PACKET_COUNT": "true", "SAI_ACL_COUNTER_ATTR_ENABLE_BYTE_COUNT": "true"},
			aclASIC + "ACL_COUNTER:" + aclTestCounterWeb:     {"SAI_ACL_COUNTER_ATTR_TABLE_ID": aclTestTable, "SAI_ACL_COUNTER_ATTR_ENABLE_PACKET_COUNT": "true", "SAI_ACL_COUNTER_ATTR_ENABLE_BYTE_COUNT": "true"},
			aclASIC + "ACL_ENTRY:" + aclTestEntryDefault: {
				"SAI_ACL_ENTRY_ATTR_TABLE_ID": aclTestTable, "SAI_ACL_ENTRY_ATTR_ADMIN_STATE": "true", "SAI_ACL_ENTRY_ATTR_PRIORITY": "1",
				"SAI_ACL_ENTRY_ATTR_ACTION_COUNTER": aclTestCounterDefault, "SAI_ACL_ENTRY_ATTR_ACTION_PACKET_ACTION": "SAI_PACKET_ACTION_DROP",
				"SAI_ACL_ENTRY_ATTR_FIELD_ACL_IP_TYPE": "SAI_ACL_IP_TYPE_IPV4ANY&mask:0xffffffffffffffff",
			},
			aclASIC + "ACL_ENTRY:" + aclTestEntryWeb: {
				"SAI_ACL_ENTRY_ATTR_TABLE_ID": aclTestTable, "SAI_ACL_ENTRY_ATTR_ADMIN_STATE": "true", "SAI_ACL_ENTRY_ATTR_PRIORITY": "100",
				"SAI_ACL_ENTRY_ATTR_ACTION_COUNTER": aclTestCounterWeb, "SAI_ACL_ENTRY_ATTR_ACTION_PACKET_ACTION": "SAI_PACKET_ACTION_FORWARD",
				"SAI_ACL_ENTRY_ATTR_FIELD_ACL_IP_TYPE": "SAI_ACL_IP_TYPE_IPV4ANY&mask:0xffffffffffffffff",
				"SAI_ACL_ENTRY_ATTR_FIELD_SRC_IP":      "192.0.2.0&mask:255.255.255.0",
				"SAI_ACL_ENTRY_ATTR_FIELD_IP_PROTOCOL": "6&mask:0xff",
				"SAI_ACL_ENTRY_ATTR_FIELD_L4_DST_PORT": "443&mask:0xffff",
			},
			aclASIC + "ACL_ENTRY:oid:0x8000000000099": {"SAI_ACL_ENTRY_ATTR_TABLE_ID": "oid:0x7000000000098"},
		},
	}
}

func aclFixtureReaders(db map[string]vlanChangeDB) (aclReader, aclScanner) {
	read := func(ctx context.Context, name, key string) (map[string]string, error) {
		return maps.Clone(db[name][key]), ctx.Err()
	}
	scan := func(ctx context.Context, name, prefix string) (vlanChangeDB, error) {
		out := vlanChangeDB{}
		for key, fields := range db[name] {
			if strings.HasPrefix(key, prefix) {
				out[key] = maps.Clone(fields)
			}
		}
		return out, ctx.Err()
	}
	return read, scan
}

func TestACLRuntimeExactTargetCounters(t *testing.T) {
	t.Parallel()
	p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
	if err != nil {
		t.Fatal(err)
	}
	read, scan := aclFixtureReaders(aclNativeFixture())
	ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, read, scan)
	if err != nil || !ok {
		t.Fatalf("%s %v", raw, err)
	}
	var observed aclObserved
	if err := json.Unmarshal(raw, &observed); err != nil {
		t.Fatal(err)
	}
	if observed.TableOID != aclTestTable || observed.AppliedRules != 2 || observed.ObservedEntries != 2 || observed.ObservedCounters != 2 || *observed.Rules["WEB"].Packets != ^uint64(0) || *observed.Rules["DEFAULT"].Packets != 0 {
		t.Fatalf("incorrect target observation %s", raw)
	}
}

func TestACLRuntimeRejectsIncompleteOrOpaqueEvidence(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name   string
		mutate func(map[string]vlanChangeDB)
	}{
		{"state pending", func(db map[string]vlanChangeDB) {
			db["STATE_DB"]["ACL_RULE_TABLE|EDGE|WEB"]["status"] = "Pending creation"
		}},
		{"missing map", func(db map[string]vlanChangeDB) { delete(db["COUNTERS_DB"]["ACL_COUNTER_RULE_MAP"], "EDGE:WEB") }},
		{"aliased counter", func(db map[string]vlanChangeDB) {
			db["COUNTERS_DB"]["ACL_COUNTER_RULE_MAP"]["OTHER:WEB"] = aclTestCounterWeb
		}},
		{"wrong table", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_COUNTER:"+aclTestCounterWeb]["SAI_ACL_COUNTER_ATTR_TABLE_ID"] = "oid:0x7000000000098"
		}},
		{"missing packets", func(db map[string]vlanChangeDB) {
			delete(db["COUNTERS_DB"]["COUNTERS:"+aclTestCounterWeb], "SAI_ACL_COUNTER_ATTR_PACKETS")
		}},
		{"counter overflow", func(db map[string]vlanChangeDB) {
			db["COUNTERS_DB"]["COUNTERS:"+aclTestCounterWeb]["SAI_ACL_COUNTER_ATTR_PACKETS"] = "18446744073709551616"
		}},
		{"extra entry", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_ENTRY:oid:0x8000000000098"] = maps.Clone(db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+aclTestEntryWeb])
		}},
		{"extra counter", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_COUNTER:oid:0x9000000000098"] = maps.Clone(db["ASIC_DB"][aclASIC+"ACL_COUNTER:"+aclTestCounterWeb])
		}},
		{"opaque action", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+aclTestEntryWeb]["SAI_ACL_ENTRY_ATTR_ACTION_REDIRECT"] = "oid:0x1000000000042"
		}},
		{"wrong mask", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+aclTestEntryWeb]["SAI_ACL_ENTRY_ATTR_FIELD_SRC_IP"] = "192.0.2.0&mask:255.255.0.0"
		}},
		{"wrong action", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+aclTestEntryDefault]["SAI_ACL_ENTRY_ATTR_ACTION_PACKET_ACTION"] = "SAI_PACKET_ACTION_FORWARD"
		}},
		{"counter disabled", func(db map[string]vlanChangeDB) {
			db["ASIC_DB"][aclASIC+"ACL_COUNTER:"+aclTestCounterDefault]["SAI_ACL_COUNTER_ATTR_ENABLE_PACKET_COUNT"] = "false"
		}},
		{"unknown target map", func(db map[string]vlanChangeDB) {
			db["COUNTERS_DB"]["ACL_COUNTER_RULE_MAP"]["EDGE:UNKNOWN"] = "oid:0x9000000000099"
		}},
		{"bound table", aclFixtureBind},
	} {
		t.Run(tc.name, func(t *testing.T) {
			db := aclNativeFixture()
			tc.mutate(db)
			read, scan := aclFixtureReaders(db)
			p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
			if err != nil {
				t.Fatal(err)
			}
			ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, read, scan)
			if err != nil || ok {
				t.Fatalf("false readiness/error: %s %v", raw, err)
			}
		})
	}
}

func aclFixtureBind(db map[string]vlanChangeDB) {
	db["ASIC_DB"][aclASIC+"PORT:"+aclTestPort]["SAI_PORT_ATTR_INGRESS_ACL"] = aclTestGroup
	db["ASIC_DB"][aclASIC+"ACL_TABLE_GROUP:"+aclTestGroup] = map[string]string{"SAI_ACL_TABLE_GROUP_ATTR_ACL_STAGE": "SAI_ACL_STAGE_INGRESS", "SAI_ACL_TABLE_GROUP_ATTR_TYPE": "SAI_ACL_TABLE_GROUP_TYPE_PARALLEL"}
	db["ASIC_DB"][aclASIC+"ACL_TABLE_GROUP_MEMBER:"+aclTestMember] = map[string]string{"SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_GROUP_ID": aclTestGroup, "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_ID": aclTestTable}
	db["ASIC_DB"]["VIDTORID"][aclTestGroup] = "oid:0x107"
	db["ASIC_DB"]["VIDTORID"][aclTestMember] = "oid:0x108"
}

func TestACLRuntimeBindingAndReadErrors(t *testing.T) {
	t.Parallel()
	db := aclNativeFixture()
	aclFixtureBind(db)
	read, scan := aclFixtureReaders(db)
	p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
	if err != nil {
		t.Fatal(err)
	}
	ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, []string{"Ethernet0"}, read, scan)
	if err != nil || !ok {
		t.Fatalf("exact binding not recognized %s %v", raw, err)
	}
	db["ASIC_DB"][aclASIC+"PORT:oid:0x1000000000042"] = map[string]string{"SAI_PORT_ATTR_INGRESS_ACL": aclTestGroup}
	if ok, _, _ := aclRuntime(t.Context(), "EDGE", p.Desired, []string{"Ethernet0"}, read, scan); ok {
		t.Fatal("unexpected extra port accepted")
	}
	broken := func(context.Context, string, string) (map[string]string, error) {
		return nil, errors.New("read denied")
	}
	if ok, _, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, broken, scan); ok || err == nil {
		t.Fatal("read failure hidden")
	}
}

func TestACLRuntimeIPv6LiteralMapping(t *testing.T) {
	t.Parallel()
	db := aclNativeFixture()
	for _, oid := range []string{aclTestEntryDefault, aclTestEntryWeb} {
		db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+oid]["SAI_ACL_ENTRY_ATTR_FIELD_ACL_IP_TYPE"] = "SAI_ACL_IP_TYPE_IPV6ANY&mask:0xffffffffffffffff"
	}
	entry := db["ASIC_DB"][aclASIC+"ACL_ENTRY:"+aclTestEntryWeb]
	delete(entry, "SAI_ACL_ENTRY_ATTR_FIELD_SRC_IP")
	delete(entry, "SAI_ACL_ENTRY_ATTR_FIELD_IP_PROTOCOL")
	entry["SAI_ACL_ENTRY_ATTR_FIELD_SRC_IPV6"] = "2001:db8::&mask:ffff:ffff::"
	entry["SAI_ACL_ENTRY_ATTR_FIELD_IPV6_NEXT_HEADER"] = "6&mask:0xff"
	table := db["ASIC_DB"][aclASIC+"ACL_TABLE:"+aclTestTable]
	delete(table, "SAI_ACL_TABLE_ATTR_FIELD_SRC_IP")
	delete(table, "SAI_ACL_TABLE_ATTR_FIELD_IP_PROTOCOL")
	table["SAI_ACL_TABLE_ATTR_FIELD_SRC_IPV6"] = "true"
	table["SAI_ACL_TABLE_ATTR_FIELD_IPV6_NEXT_HEADER"] = "true"
	spec := strings.NewReplacer("IPv4", "IPv6", "192.0.2.0/24", "2001:db8::/32").Replace(aclTestSpec)
	p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", spec))
	if err != nil {
		t.Fatal(err)
	}
	read, scan := aclFixtureReaders(db)
	if ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, read, scan); err != nil || !ok {
		t.Fatalf("IPv6 mapping %s %v", raw, err)
	}
}

func TestACLRuntimeRequiresAppliedObjectChain(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct{ name, vid string }{
		{"table", aclTestTable}, {"entry", aclTestEntryWeb}, {"counter", aclTestCounterWeb},
		{"port", aclTestPort}, {"group", aclTestGroup}, {"group member", aclTestMember},
	} {
		for _, mode := range []string{"missing translation", "null RID", "invalid RID", "overflow RID", "aliased RID", "wrong VID type", "extension VID type"} {
			t.Run(tc.name+"/"+mode, func(t *testing.T) {
				db := aclNativeFixture()
				aclFixtureBind(db)
				ids := db["ASIC_DB"]["VIDTORID"]
				switch mode {
				case "missing translation":
					delete(ids, tc.vid)
				case "null RID":
					ids[tc.vid] = "oid:0x0"
				case "invalid RID":
					ids[tc.vid] = "pending"
				case "overflow RID":
					ids[tc.vid] = "oid:0x10000000000000000"
				case "aliased RID":
					ids["oid:0x1000000000099"] = ids[tc.vid]
				case "wrong VID type":
					aclFixtureReplaceOID(db, tc.vid, "oid:0x3000000000099")
				case "extension VID type":
					// Same base type byte but the sairedis extension flag is set.
					aclFixtureReplaceOID(db, tc.vid, strings.Replace(tc.vid, "0000000000", "0080000000", 1))
				}
				p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
				if err != nil {
					t.Fatal(err)
				}
				read, scan := aclFixtureReaders(db)
				ok, raw, _ := aclRuntime(t.Context(), "EDGE", p.Desired, []string{"Ethernet0"}, read, scan)
				if ok {
					t.Fatalf("unapplied/wrong-type %s qualified: %s", tc.name, raw)
				}
			})
		}
	}
	t.Run("unbound requested records without translations", func(t *testing.T) {
		db := aclNativeFixture()
		delete(db["ASIC_DB"], "VIDTORID")
		read, scan := aclFixtureReaders(db)
		p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
		if err != nil {
			t.Fatal(err)
		}
		ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, read, scan)
		if ok || err != nil {
			t.Fatalf("pending observation: %s %v", raw, err)
		}
	})
}

// Rewrite the entire fixture's references as well as keys so wrong-type tests
// remain fully correlated and fail specifically on the object's VID type.
func aclFixtureReplaceOID(db map[string]vlanChangeDB, old, replacement string) {
	for _, objects := range db {
		updated := vlanChangeDB{}
		for key, fields := range objects {
			out := map[string]string{}
			for field, value := range fields {
				out[strings.ReplaceAll(field, old, replacement)] = strings.ReplaceAll(value, old, replacement)
			}
			updated[strings.ReplaceAll(key, old, replacement)] = out
		}
		clear(objects)
		maps.Copy(objects, updated)
	}
}

func TestACLRuntimeLAGTranslation(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"applied", "missing translation", "wrong type"} {
		t.Run(mode, func(t *testing.T) {
			db := aclNativeFixture()
			aclFixtureBind(db)
			delete(db["ASIC_DB"], aclASIC+"PORT:"+aclTestPort)
			db["ASIC_DB"][aclASIC+"LAG:"+aclTestLAG] = map[string]string{"SAI_LAG_ATTR_INGRESS_ACL": aclTestGroup}
			db["ASIC_DB"]["VIDTORID"][aclTestLAG] = "oid:0x109"
			db["COUNTERS_DB"]["COUNTERS_LAG_NAME_MAP"] = map[string]string{"PortChannel1": aclTestLAG}
			db["STATE_DB"]["LAG_TABLE|PortChannel1"] = map[string]string{"state": "ok"}
			if mode == "missing translation" {
				delete(db["ASIC_DB"]["VIDTORID"], aclTestLAG)
			}
			if mode == "wrong type" {
				aclFixtureReplaceOID(db, aclTestLAG, "oid:0x1000000000071")
			}
			read, scan := aclFixtureReaders(db)
			p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
			if err != nil {
				t.Fatal(err)
			}
			ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, []string{"PortChannel1"}, read, scan)
			if ok != (mode == "applied") || (ok && err != nil) {
				t.Fatalf("LAG %s: %s %v", mode, raw, err)
			}
		})
	}
}

func TestACLRuntimeTranslationReadAndChurn(t *testing.T) {
	t.Parallel()
	for _, mode := range []string{"read error", "removed during observation", "replaced during observation"} {
		t.Run(mode, func(t *testing.T) {
			db := aclNativeFixture()
			read, scan := aclFixtureReaders(db)
			reads := 0
			wrapped := func(ctx context.Context, name, key string) (map[string]string, error) {
				if name == "ASIC_DB" && key == "VIDTORID" {
					reads++
					if mode == "read error" {
						return nil, errors.New("translation read denied")
					}
					if reads > 1 {
						if mode == "removed during observation" {
							delete(db["ASIC_DB"]["VIDTORID"], aclTestEntryWeb)
						} else {
							db["ASIC_DB"]["VIDTORID"][aclTestEntryWeb] = "oid:0x200"
						}
					}
				}
				return read(ctx, name, key)
			}
			p, err := planNetworkACLPolicy(nil, aclRequest("ACLPolicy", aclTestSpec))
			if err != nil {
				t.Fatal(err)
			}
			ok, raw, err := aclRuntime(t.Context(), "EDGE", p.Desired, nil, wrapped, scan)
			if ok || ((err != nil) != (mode == "read error")) {
				t.Fatalf("translation failure hidden: %s %v", raw, err)
			}
		})
	}
}
