# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/sonic.networking.metal.ironcore.dev_switches.yaml
- bases/sonic.networking.metal.ironcore.dev_switchinterfaces.yaml
- bases/sonic.networking.metal.ironcore.dev_switchcredentials.yaml
- bases/sonic.networking.metal.ironcore.dev_switchvlans.yaml
- bases/sonic.networking.metal.ironcore.dev_switchportbreakouts.yaml
- bases/sonic.networking.metal.ironcore.dev_switchportchannels.yaml
- bases/sonic.networking.metal.ironcore.dev_switchvrfs.yaml
- bases/sonic.networking.metal.ironcore.dev_switchl3interfaces.yaml
- bases/sonic.networking.metal.ironcore.dev_switchstaticroutes.yaml
- bases/sonic.networking.metal.ironcore.dev_switchbgps.yaml
- bases/sonic.networking.metal.ironcore.dev_switchbgppeers.yaml
- bases/sonic.networking.metal.ironcore.dev_switchdhcprelays.yaml
- bases/sonic.networking.metal.ironcore.dev_switchfrrmigrations.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
